/**
 * \file	
 * 
 * \brief	ISP Register Map
 * 
 * \author 	frank
 * 
 * \version 0.1
 *
 * Revision History
 * 
 * 
 * Copyright (c) 2016 Pixelplus Co.,Ltd. All rights reserved
 *
 */
#ifndef __ISPREG_H__
#define __ISPREG_H__

#ifdef __cplusplus
extern "C" {
#endif

#define BASE_ADDR_MVI			(0xF0900C00U)
#define BASE_ADDR_ISP			(0xF0600000U)

#define BANK_A					0x0
#define BANK_B					0x1
#define BANK_C					0x2
#define BANK_D					0x3
#define BANK_E					0x4
#define BANK_F					0x5

#define REG_FB_R_REF0                (BASE_ADDR_ISP + 0x10  )
#define REG_FB_R_REF1                (BASE_ADDR_ISP + 0x14  )
#define REG_FB_R_REF2                (BASE_ADDR_ISP + 0x18  )
#define REG_FB_R_REF3                (BASE_ADDR_ISP + 0x1C  )
#define REG_FB_R_REF4                (BASE_ADDR_ISP + 0x20  )
#define REG_FB_GR_REF0               (BASE_ADDR_ISP + 0x24  )
#define REG_FB_GR_REF1               (BASE_ADDR_ISP + 0x28  )
#define REG_FB_GR_REF2               (BASE_ADDR_ISP + 0x2C  )
#define REG_FB_GR_REF3               (BASE_ADDR_ISP + 0x30  )
#define REG_FB_GR_REF4               (BASE_ADDR_ISP + 0x34  )
#define REG_FB_GB_REF0               (BASE_ADDR_ISP + 0x38  )
#define REG_FB_GB_REF1               (BASE_ADDR_ISP + 0x3C  )
#define REG_FB_GB_REF2               (BASE_ADDR_ISP + 0x40  )
#define REG_FB_GB_REF3               (BASE_ADDR_ISP + 0x44  )
#define REG_FB_GB_REF4               (BASE_ADDR_ISP + 0x48  )
#define REG_FB_B_REF0                (BASE_ADDR_ISP + 0x4C  )
#define REG_FB_B_REF1                (BASE_ADDR_ISP + 0x50  )
#define REG_FB_B_REF2                (BASE_ADDR_ISP + 0x54  )
#define REG_FB_B_REF3                (BASE_ADDR_ISP + 0x58  )
#define REG_FB_B_REF4                (BASE_ADDR_ISP + 0x5C  )
#define REG_PDST_R_REF0              (BASE_ADDR_ISP + 0x60  )
#define REG_PDST_R_REF1              (BASE_ADDR_ISP + 0x64  )
#define REG_PDST_R_REF2              (BASE_ADDR_ISP + 0x68  )
#define REG_PDST_R_REF3              (BASE_ADDR_ISP + 0x6C  )
#define REG_PDST_R_REF4              (BASE_ADDR_ISP + 0x70  )
#define REG_PDST_GR_REF0             (BASE_ADDR_ISP + 0x74  )
#define REG_PDST_GR_REF1             (BASE_ADDR_ISP + 0x78  )
#define REG_PDST_GR_REF2             (BASE_ADDR_ISP + 0x7C  )
#define REG_PDST_GR_REF3             (BASE_ADDR_ISP + 0x80  )
#define REG_PDST_GR_REF4             (BASE_ADDR_ISP + 0x84  )
#define REG_PDST_GB_REF0             (BASE_ADDR_ISP + 0x88  )
#define REG_PDST_GB_REF1             (BASE_ADDR_ISP + 0x8C  )
#define REG_PDST_GB_REF2             (BASE_ADDR_ISP + 0x90  )
#define REG_PDST_GB_REF3             (BASE_ADDR_ISP + 0x94  )
#define REG_PDST_GB_REF4             (BASE_ADDR_ISP + 0x98  )
#define REG_PDST_B_REF0              (BASE_ADDR_ISP + 0x9C  )
#define REG_PDST_B_REF1              (BASE_ADDR_ISP + 0xA0  )
#define REG_PDST_B_REF2              (BASE_ADDR_ISP + 0xA4  )
#define REG_PDST_B_REF3              (BASE_ADDR_ISP + 0xA8  )
#define REG_PDST_B_REF4              (BASE_ADDR_ISP + 0xAC  )
#define REG_DARK_DPC_P0              (BASE_ADDR_ISP + 0xB0  )
#define REG_DARK_DPC_P1              (BASE_ADDR_ISP + 0xB4  )
#define REG_DARK_DPC_P2              (BASE_ADDR_ISP + 0xB8  )
#define REG_DARK_DPC_N0              (BASE_ADDR_ISP + 0xBC  )
#define REG_DARK_DPC_N1              (BASE_ADDR_ISP + 0xC0  )
#define REG_DARK_DPC_N2              (BASE_ADDR_ISP + 0xC4  )
#define REG_DARK_BLF_REF0            (BASE_ADDR_ISP + 0xC8  )
#define REG_DARK_BLF_REF1            (BASE_ADDR_ISP + 0xCC  )
#define REG_DARK_BLF_REF2            (BASE_ADDR_ISP + 0xD0  )
#define REG_DARK_BLF_REF3            (BASE_ADDR_ISP + 0xD4  )
#define REG_DARK_BLF_REF4            (BASE_ADDR_ISP + 0xD8  )
#define REG_DARK_NF_REF0             (BASE_ADDR_ISP + 0xDC  )
#define REG_DARK_NF_REF1             (BASE_ADDR_ISP + 0xE0  )
#define REG_DARK_NF_REF2             (BASE_ADDR_ISP + 0xE4  )
#define REG_DARK_NF_REF3             (BASE_ADDR_ISP + 0xE8  )
#define REG_DARK_NF_REF4             (BASE_ADDR_ISP + 0xEC  )
#define REG_BLF_W0_REF0              (BASE_ADDR_ISP + 0xF0  )
#define REG_BLF_W0_REF1              (BASE_ADDR_ISP + 0xF4  )
#define REG_BLF_W0_REF2              (BASE_ADDR_ISP + 0xF8  )
#define REG_BLF_W0_REF3              (BASE_ADDR_ISP + 0xFC  )
#define REG_BLF_W0_REF4              (BASE_ADDR_ISP + 0x100 )
#define REG_NR_NA0                   (BASE_ADDR_ISP + 0x104 )
#define REG_NR_NA1                   (BASE_ADDR_ISP + 0x108 )
#define REG_NR_NA2                   (BASE_ADDR_ISP + 0x10C )
#define REG_NR_NA3                   (BASE_ADDR_ISP + 0x110 )
#define REG_NR_NA4                   (BASE_ADDR_ISP + 0x114 )
#define REG_NR_NB0                   (BASE_ADDR_ISP + 0x118 )
#define REG_NR_NB1                   (BASE_ADDR_ISP + 0x11C )
#define REG_NR_NB2                   (BASE_ADDR_ISP + 0x120 )
#define REG_NR_NB3                   (BASE_ADDR_ISP + 0x124 )
#define REG_NR_NB4                   (BASE_ADDR_ISP + 0x128 )
#define REG_NR_XREF0                 (BASE_ADDR_ISP + 0x12C )
#define REG_NR_XREF1                 (BASE_ADDR_ISP + 0x130 )
#define REG_NR_XREF2                 (BASE_ADDR_ISP + 0x134 )
#define REG_NR_XREF3                 (BASE_ADDR_ISP + 0x138 )
#define REG_NR_XREF4                 (BASE_ADDR_ISP + 0x13C )
#define REG_NR_SGAIN0                (BASE_ADDR_ISP + 0x140 )
#define REG_NR_SGAIN1                (BASE_ADDR_ISP + 0x144 )
#define REG_NR_SGAIN2                (BASE_ADDR_ISP + 0x148 )
#define REG_NR_SGAIN3                (BASE_ADDR_ISP + 0x14C )
#define REG_NR_SGAIN4                (BASE_ADDR_ISP + 0x150 )
#define REG_FCMSCL_REF0              (BASE_ADDR_ISP + 0x154 )
#define REG_FCMSCL_REF1              (BASE_ADDR_ISP + 0x158 )
#define REG_FCMSCL_REF2              (BASE_ADDR_ISP + 0x15C )
#define REG_FCMSCL_REF3              (BASE_ADDR_ISP + 0x160 )
#define REG_FCMSCL_REF4              (BASE_ADDR_ISP + 0x164 )
#define REG_FCHSCL_REF0              (BASE_ADDR_ISP + 0x168 )
#define REG_FCHSCL_REF1              (BASE_ADDR_ISP + 0x16C )
#define REG_FCHSCL_REF2              (BASE_ADDR_ISP + 0x170 )
#define REG_FCHSCL_REF3              (BASE_ADDR_ISP + 0x174 )
#define REG_FCHSCL_REF4              (BASE_ADDR_ISP + 0x178 )
#define REG_EDGETH_REF0              (BASE_ADDR_ISP + 0x17C )
#define REG_EDGETH_REF1              (BASE_ADDR_ISP + 0x180 )
#define REG_EDGETH_REF2              (BASE_ADDR_ISP + 0x184 )
#define REG_EDGETH_REF3              (BASE_ADDR_ISP + 0x188 )
#define REG_EDGETH_REF4              (BASE_ADDR_ISP + 0x18C )
#define REG_YMCOR_REF0               (BASE_ADDR_ISP + 0x190 )
#define REG_YMCOR_REF1               (BASE_ADDR_ISP + 0x194 )
#define REG_YMCOR_REF2               (BASE_ADDR_ISP + 0x198 )
#define REG_YMCOR_REF3               (BASE_ADDR_ISP + 0x19C )
#define REG_YMCOR_REF4               (BASE_ADDR_ISP + 0x1A0 )
#define REG_YHCOR_REF0               (BASE_ADDR_ISP + 0x1A4 )
#define REG_YHCOR_REF1               (BASE_ADDR_ISP + 0x1A8 )
#define REG_YHCOR_REF2               (BASE_ADDR_ISP + 0x1AC )
#define REG_YHCOR_REF3               (BASE_ADDR_ISP + 0x1B0 )
#define REG_YHCOR_REF4               (BASE_ADDR_ISP + 0x1B4 )
#define REG_YMGAIN_REF0              (BASE_ADDR_ISP + 0x1B8 )
#define REG_YMGAIN_REF1              (BASE_ADDR_ISP + 0x1BC )
#define REG_YMGAIN_REF2              (BASE_ADDR_ISP + 0x1C0 )
#define REG_YMGAIN_REF3              (BASE_ADDR_ISP + 0x1C4 )
#define REG_YMGAIN_REF4              (BASE_ADDR_ISP + 0x1C8 )
#define REG_YHGAIN_REF0              (BASE_ADDR_ISP + 0x1CC )
#define REG_YHGAIN_REF1              (BASE_ADDR_ISP + 0x1D0 )
#define REG_YHGAIN_REF2              (BASE_ADDR_ISP + 0x1D4 )
#define REG_YHGAIN_REF3              (BASE_ADDR_ISP + 0x1D8 )
#define REG_YHGAIN_REF4              (BASE_ADDR_ISP + 0x1DC )
#define REG_DARK_E_RGB_GM0           (BASE_ADDR_ISP + 0x1E0 )
#define REG_DARK_E_RGB_GM1           (BASE_ADDR_ISP + 0x1E4 )
#define REG_DARK_E_RGB_GM2           (BASE_ADDR_ISP + 0x1E8 )
#define REG_DARK_E_GM0               (BASE_ADDR_ISP + 0x1EC )
#define REG_DARK_E_GM1               (BASE_ADDR_ISP + 0x1F0 )
#define REG_DARK_E_GM2               (BASE_ADDR_ISP + 0x1F4 )
#define REG_EDGE_PGAIN0              (BASE_ADDR_ISP + 0x1F8 )
#define REG_EDGE_PGAIN1              (BASE_ADDR_ISP + 0x1FC )
#define REG_EDGE_PGAIN2              (BASE_ADDR_ISP + 0x200 )
#define REG_EDGE_PGAIN3              (BASE_ADDR_ISP + 0x204 )
#define REG_EDGE_PGAIN4              (BASE_ADDR_ISP + 0x208 )
#define REG_EDGE_MGAIN0              (BASE_ADDR_ISP + 0x20C )
#define REG_EDGE_MGAIN1              (BASE_ADDR_ISP + 0x210 )
#define REG_EDGE_MGAIN2              (BASE_ADDR_ISP + 0x214 )
#define REG_EDGE_MGAIN3              (BASE_ADDR_ISP + 0x218 )
#define REG_EDGE_MGAIN4              (BASE_ADDR_ISP + 0x21C )
#define REG_DARK_GAUS_K0_0           (BASE_ADDR_ISP + 0x220 )
#define REG_DARK_GAUS_K0_1           (BASE_ADDR_ISP + 0x224 )
#define REG_DARK_GAUS_K0_2           (BASE_ADDR_ISP + 0x228 )
#define REG_DARK_GAUS_K0_3           (BASE_ADDR_ISP + 0x22C )
#define REG_DARK_GAUS_K0_4           (BASE_ADDR_ISP + 0x230 )
#define REG_DARK_EC_PMAX0            (BASE_ADDR_ISP + 0x234 )
#define REG_DARK_EC_PMAX1            (BASE_ADDR_ISP + 0x238 )
#define REG_DARK_EC_PMAX2            (BASE_ADDR_ISP + 0x23C )
#define REG_DARK_EC_MMAX0            (BASE_ADDR_ISP + 0x240 )
#define REG_DARK_EC_MMAX1            (BASE_ADDR_ISP + 0x244 )
#define REG_DARK_EC_MMAX2            (BASE_ADDR_ISP + 0x248 )
#define REG_DARK_EC_PTH0             (BASE_ADDR_ISP + 0x24C )
#define REG_DARK_EC_PTH1             (BASE_ADDR_ISP + 0x250 )
#define REG_DARK_EC_PTH2             (BASE_ADDR_ISP + 0x254 )
#define REG_DARK_EC_PTH3             (BASE_ADDR_ISP + 0x258 )
#define REG_DARK_EC_PTH4             (BASE_ADDR_ISP + 0x25C )
#define REG_DARK_EC_MTH0             (BASE_ADDR_ISP + 0x260 )
#define REG_DARK_EC_MTH1             (BASE_ADDR_ISP + 0x264 )
#define REG_DARK_EC_MTH2             (BASE_ADDR_ISP + 0x268 )
#define REG_DARK_EC_MTH3             (BASE_ADDR_ISP + 0x26C )
#define REG_DARK_EC_MTH4             (BASE_ADDR_ISP + 0x270 )
#define REG_WB_ATTEN_REF0            (BASE_ADDR_ISP + 0x274 )
#define REG_WB_ATTEN_REF1            (BASE_ADDR_ISP + 0x278 )
#define REG_WB_ATTEN_REF2            (BASE_ADDR_ISP + 0x27C )
#define REG_WB_ATTEN_REF3            (BASE_ADDR_ISP + 0x280 )
#define REG_WB_ATTEN_REF4            (BASE_ADDR_ISP + 0x284 )
#define REG_DARK_Y_GM0               (BASE_ADDR_ISP + 0x288 )
#define REG_DARK_Y_GM1               (BASE_ADDR_ISP + 0x28C )
#define REG_DARK_Y_GM2               (BASE_ADDR_ISP + 0x290 )
#define REG_DARK_Y_GM3               (BASE_ADDR_ISP + 0x294 )
#define REG_DARK_Y_GM4               (BASE_ADDR_ISP + 0x298 )
#define REG_YBRIGHTNESS_REF0         (BASE_ADDR_ISP + 0x29C )
#define REG_YBRIGHTNESS_REF1         (BASE_ADDR_ISP + 0x2A0 )
#define REG_YBRIGHTNESS_REF2         (BASE_ADDR_ISP + 0x2A4 )
#define REG_YBRIGHTNESS_REF3         (BASE_ADDR_ISP + 0x2A8 )
#define REG_YBRIGHTNESS_REF4         (BASE_ADDR_ISP + 0x2AC )
#define REG_Y_CONT_TH2_REF0          (BASE_ADDR_ISP + 0x2B0 )
#define REG_Y_CONT_TH2_REF1          (BASE_ADDR_ISP + 0x2B4 )
#define REG_Y_CONT_TH2_REF2          (BASE_ADDR_ISP + 0x2B8 )
#define REG_Y_CONT_TH2_REF3          (BASE_ADDR_ISP + 0x2BC )
#define REG_Y_CONT_TH2_REF4          (BASE_ADDR_ISP + 0x2C0 )
#define REG_Y_CONT_SLOPE2_REF0       (BASE_ADDR_ISP + 0x2C4 )
#define REG_Y_CONT_SLOPE2_REF1       (BASE_ADDR_ISP + 0x2C8 )
#define REG_Y_CONT_SLOPE2_REF2       (BASE_ADDR_ISP + 0x2CC )
#define REG_Y_CONT_SLOPE2_REF3       (BASE_ADDR_ISP + 0x2D0 )
#define REG_Y_CONT_SLOPE2_REF4       (BASE_ADDR_ISP + 0x2D4 )
#define REG_CCR_HR_WT_REF0           (BASE_ADDR_ISP + 0x2D8 )
#define REG_CCR_HR_WT_REF1           (BASE_ADDR_ISP + 0x2DC )
#define REG_CCR_HR_WT_REF2           (BASE_ADDR_ISP + 0x2E0 )
#define REG_CCR_HR_WT_REF3           (BASE_ADDR_ISP + 0x2E4 )
#define REG_CCR_HR_WT_REF4           (BASE_ADDR_ISP + 0x2E8 )
#define REG_CCR_M11_A                (BASE_ADDR_ISP + 0x2EC )
#define REG_CCR_M11_B                (BASE_ADDR_ISP + 0x2F0 )
#define REG_CCR_M11_C                (BASE_ADDR_ISP + 0x2F4 )
#define REG_CCR_M12_A                (BASE_ADDR_ISP + 0x2F8 )
#define REG_CCR_M12_B                (BASE_ADDR_ISP + 0x2FC )
#define REG_CCR_M12_C                (BASE_ADDR_ISP + 0x300 )
#define REG_CCR_M13_A                (BASE_ADDR_ISP + 0x304 )
#define REG_CCR_M13_B                (BASE_ADDR_ISP + 0x308 )
#define REG_CCR_M13_C                (BASE_ADDR_ISP + 0x30C )
#define REG_CCR_M21_A                (BASE_ADDR_ISP + 0x310 )
#define REG_CCR_M21_B                (BASE_ADDR_ISP + 0x314 )
#define REG_CCR_M21_C                (BASE_ADDR_ISP + 0x318 )
#define REG_CCR_M22_A                (BASE_ADDR_ISP + 0x31C )
#define REG_CCR_M22_B                (BASE_ADDR_ISP + 0x320 )
#define REG_CCR_M22_C                (BASE_ADDR_ISP + 0x324 )
#define REG_CCR_M23_A                (BASE_ADDR_ISP + 0x328 )
#define REG_CCR_M23_B                (BASE_ADDR_ISP + 0x32C )
#define REG_CCR_M23_C                (BASE_ADDR_ISP + 0x330 )
#define REG_CCR_M31_A                (BASE_ADDR_ISP + 0x334 )
#define REG_CCR_M31_B                (BASE_ADDR_ISP + 0x338 )
#define REG_CCR_M31_C                (BASE_ADDR_ISP + 0x33C )
#define REG_CCR_M32_A                (BASE_ADDR_ISP + 0x340 )
#define REG_CCR_M32_B                (BASE_ADDR_ISP + 0x344 )
#define REG_CCR_M32_C                (BASE_ADDR_ISP + 0x348 )
#define REG_CCR_M33_A                (BASE_ADDR_ISP + 0x34C )
#define REG_CCR_M33_B                (BASE_ADDR_ISP + 0x350 )
#define REG_CCR_M33_C                (BASE_ADDR_ISP + 0x354 )
#define REG_DARK_CCR0                (BASE_ADDR_ISP + 0x358 )
#define REG_DARK_CCR1                (BASE_ADDR_ISP + 0x35C )
#define REG_DARK_CCR2                (BASE_ADDR_ISP + 0x360 )
#define REG_CBASE_HR_WT_REF0         (BASE_ADDR_ISP + 0x364 )
#define REG_CBASE_HR_WT_REF1         (BASE_ADDR_ISP + 0x368 )
#define REG_CBASE_HR_WT_REF2         (BASE_ADDR_ISP + 0x36C )
#define REG_CBASE_HR_WT_REF3         (BASE_ADDR_ISP + 0x370 )
#define REG_CBASE_HR_WT_REF4         (BASE_ADDR_ISP + 0x374 )
#define REG_DARK_RGB_GM0             (BASE_ADDR_ISP + 0x378 )
#define REG_DARK_RGB_GM1             (BASE_ADDR_ISP + 0x37C )
#define REG_DARK_RGB_GM2             (BASE_ADDR_ISP + 0x380 )
#define REG_DARK_RGB_GM3             (BASE_ADDR_ISP + 0x384 )
#define REG_DARK_RGB_GM4             (BASE_ADDR_ISP + 0x388 )
#define REG_Y_WEIGHT_REF0            (BASE_ADDR_ISP + 0x38C )
#define REG_Y_WEIGHT_REF1            (BASE_ADDR_ISP + 0x390 )
#define REG_Y_WEIGHT_REF2            (BASE_ADDR_ISP + 0x394 )
#define REG_Y_WEIGHT_REF3            (BASE_ADDR_ISP + 0x398 )
#define REG_Y_WEIGHT_REF4            (BASE_ADDR_ISP + 0x39C )
#define REG_DARK_DC0                 (BASE_ADDR_ISP + 0x3A0 )
#define REG_DARK_DC1                 (BASE_ADDR_ISP + 0x3A4 )
#define REG_DARK_DC2                 (BASE_ADDR_ISP + 0x3A8 )
#define REG_DARK_DC_Y10              (BASE_ADDR_ISP + 0x3AC )
#define REG_DARK_DC_Y11              (BASE_ADDR_ISP + 0x3B0 )
#define REG_DARK_DC_Y12              (BASE_ADDR_ISP + 0x3B4 )
#define REG_AXIS_A                   (BASE_ADDR_ISP + 0x410 )
#define REG_AXIS_B                   (BASE_ADDR_ISP + 0x414 )
#define REG_AXIS_C                   (BASE_ADDR_ISP + 0x418 )
#define REG_CS11_A                   (BASE_ADDR_ISP + 0x41C )
#define REG_CS11_B                   (BASE_ADDR_ISP + 0x420 )
#define REG_CS11_C                   (BASE_ADDR_ISP + 0x424 )
#define REG_CS12_A                   (BASE_ADDR_ISP + 0x428 )
#define REG_CS12_B                   (BASE_ADDR_ISP + 0x42C )
#define REG_CS12_C                   (BASE_ADDR_ISP + 0x430 )
#define REG_CS21_A                   (BASE_ADDR_ISP + 0x434 )
#define REG_CS21_B                   (BASE_ADDR_ISP + 0x438 )
#define REG_CS21_C                   (BASE_ADDR_ISP + 0x43C )
#define REG_CS22_A                   (BASE_ADDR_ISP + 0x440 )
#define REG_CS22_B                   (BASE_ADDR_ISP + 0x444 )
#define REG_CS22_C                   (BASE_ADDR_ISP + 0x448 )
#define REG_VEC_H0_A                 (BASE_ADDR_ISP + 0x44C )
#define REG_VEC_H0_B                 (BASE_ADDR_ISP + 0x450 )
#define REG_VEC_H0_C                 (BASE_ADDR_ISP + 0x454 )
#define REG_VEC_S0_A                 (BASE_ADDR_ISP + 0x458 )
#define REG_VEC_S0_B                 (BASE_ADDR_ISP + 0x45C )
#define REG_VEC_S0_C                 (BASE_ADDR_ISP + 0x460 )
#define REG_VEC_H1_A                 (BASE_ADDR_ISP + 0x464 )
#define REG_VEC_H1_B                 (BASE_ADDR_ISP + 0x468 )
#define REG_VEC_H1_C                 (BASE_ADDR_ISP + 0x46C )
#define REG_VEC_S1_A                 (BASE_ADDR_ISP + 0x470 )
#define REG_VEC_S1_B                 (BASE_ADDR_ISP + 0x474 )
#define REG_VEC_S1_C                 (BASE_ADDR_ISP + 0x478 )
#define REG_VEC_H2_A                 (BASE_ADDR_ISP + 0x47C )
#define REG_VEC_H2_B                 (BASE_ADDR_ISP + 0x480 )
#define REG_VEC_H2_C                 (BASE_ADDR_ISP + 0x484 )
#define REG_VEC_S2_A                 (BASE_ADDR_ISP + 0x488 )
#define REG_VEC_S2_B                 (BASE_ADDR_ISP + 0x48C )
#define REG_VEC_S2_C                 (BASE_ADDR_ISP + 0x490 )
#define REG_VEC_H3_A                 (BASE_ADDR_ISP + 0x494 )
#define REG_VEC_H3_B                 (BASE_ADDR_ISP + 0x498 )
#define REG_VEC_H3_C                 (BASE_ADDR_ISP + 0x49C )
#define REG_VEC_S3_A                 (BASE_ADDR_ISP + 0x4A0 )
#define REG_VEC_S3_B                 (BASE_ADDR_ISP + 0x4A4 )
#define REG_VEC_S3_C                 (BASE_ADDR_ISP + 0x4A8 )
#define REG_VEC_H4_A                 (BASE_ADDR_ISP + 0x4AC )
#define REG_VEC_H4_B                 (BASE_ADDR_ISP + 0x4B0 )
#define REG_VEC_H4_C                 (BASE_ADDR_ISP + 0x4B4 )
#define REG_VEC_S4_A                 (BASE_ADDR_ISP + 0x4B8 )
#define REG_VEC_S4_B                 (BASE_ADDR_ISP + 0x4BC )
#define REG_VEC_S4_C                 (BASE_ADDR_ISP + 0x4C0 )
#define REG_VEC_H5_A                 (BASE_ADDR_ISP + 0x4C4 )
#define REG_VEC_H5_B                 (BASE_ADDR_ISP + 0x4C8 )
#define REG_VEC_H5_C                 (BASE_ADDR_ISP + 0x4CC )
#define REG_VEC_S5_A                 (BASE_ADDR_ISP + 0x4D0 )
#define REG_VEC_S5_B                 (BASE_ADDR_ISP + 0x4D4 )
#define REG_VEC_S5_C                 (BASE_ADDR_ISP + 0x4D8 )
#define REG_POST_PEGAIN0             (BASE_ADDR_ISP + 0x4DC )
#define REG_POST_PEGAIN1             (BASE_ADDR_ISP + 0x4E0 )
#define REG_POST_PEGAIN2             (BASE_ADDR_ISP + 0x4E4 )
#define REG_POST_MEGAIN0             (BASE_ADDR_ISP + 0x4E8 )
#define REG_POST_MEGAIN1             (BASE_ADDR_ISP + 0x4EC )
#define REG_POST_MEGAIN2             (BASE_ADDR_ISP + 0x4F0 )
#define REG_DUMMY0                   (BASE_ADDR_ISP + 0x4F8 )
#define REG_DUMMY1                   (BASE_ADDR_ISP + 0x4FC )
#define REG_DUMMY2                   (BASE_ADDR_ISP + 0x500 )
#define REG_DUMMY3                   (BASE_ADDR_ISP + 0x504 )
#define REG_DUMMY4                   (BASE_ADDR_ISP + 0x508 )
#define REG_DUMMY5                   (BASE_ADDR_ISP + 0x50C )
#define REG_DUMMY6                   (BASE_ADDR_ISP + 0x510 )
#define REG_DUMMY7                   (BASE_ADDR_ISP + 0x514 )
#define REG_DUMMY8                   (BASE_ADDR_ISP + 0x518 )
#define REG_DUMMY9                   (BASE_ADDR_ISP + 0x51C )
#define REG_DUMMY10                  (BASE_ADDR_ISP + 0x520 )
#define REG_DUMMY11                  (BASE_ADDR_ISP + 0x524 )
#define REG_DUMMY12                  (BASE_ADDR_ISP + 0x528 )
#define REG_DUMMY13                  (BASE_ADDR_ISP + 0x52C )
#define REG_DUMMY14                  (BASE_ADDR_ISP + 0x530 )
#define REG_DUMMY15                  (BASE_ADDR_ISP + 0x534 )
#define REG_DUMMY16                  (BASE_ADDR_ISP + 0x538 )
#define REG_DUMMY17                  (BASE_ADDR_ISP + 0x53C )
#define REG_DUMMY18                  (BASE_ADDR_ISP + 0x540 )
#define REG_DUMMY19                  (BASE_ADDR_ISP + 0x544 )
#define REG_DUMMY20                  (BASE_ADDR_ISP + 0x548 )
#define REG_DUMMY21                  (BASE_ADDR_ISP + 0x54C )
#define REG_DUMMY22                  (BASE_ADDR_ISP + 0x550 )
#define REG_DUMMY23                  (BASE_ADDR_ISP + 0x554 )
#define REG_DUMMY24                  (BASE_ADDR_ISP + 0x558 )
#define REG_DUMMY25                  (BASE_ADDR_ISP + 0x55C )
#define REG_DUMMY26                  (BASE_ADDR_ISP + 0x560 )
#define REG_DUMMY27                  (BASE_ADDR_ISP + 0x564 )
#define REG_DUMMY28                  (BASE_ADDR_ISP + 0x568 )
#define REG_DUMMY29                  (BASE_ADDR_ISP + 0x56C )
#define REG_DUMMY30                  (BASE_ADDR_ISP + 0x570 )
#define REG_DUMMY31                  (BASE_ADDR_ISP + 0x574 )
#define REG_DUMMY32                  (BASE_ADDR_ISP + 0x578 )
#define REG_DUMMY33                  (BASE_ADDR_ISP + 0x57C )
#define REG_DUMMY34                  (BASE_ADDR_ISP + 0x580 )
#define REG_DUMMY35                  (BASE_ADDR_ISP + 0x584 )
#define REG_DUMMY36                  (BASE_ADDR_ISP + 0x588 )
#define REG_DUMMY37                  (BASE_ADDR_ISP + 0x58C )
#define REG_DUMMY38                  (BASE_ADDR_ISP + 0x590 )
#define REG_DUMMY39                  (BASE_ADDR_ISP + 0x594 )
#define REG_DUMMY40                  (BASE_ADDR_ISP + 0x598 )
#define REG_DUMMY41                  (BASE_ADDR_ISP + 0x59C )
#define REG_DUMMY42                  (BASE_ADDR_ISP + 0x5A0 )
#define REG_DUMMY43                  (BASE_ADDR_ISP + 0x5A4 )
#define REG_DUMMY44                  (BASE_ADDR_ISP + 0x5A8 )
#define REG_DUMMY45                  (BASE_ADDR_ISP + 0x5AC )
#define REG_DUMMY46                  (BASE_ADDR_ISP + 0x5B0 )
#define REG_DUMMY47                  (BASE_ADDR_ISP + 0x5B4 )
#define REG_DUMMY48                  (BASE_ADDR_ISP + 0x5B8 )
#define REG_DUMMY49                  (BASE_ADDR_ISP + 0x5BC )
#define REG_DUMMY50                  (BASE_ADDR_ISP + 0x5C0 )
#define REG_DUMMY51                  (BASE_ADDR_ISP + 0x5C4 )
#define REG_DUMMY52                  (BASE_ADDR_ISP + 0x5C8 )
#define REG_DUMMY53                  (BASE_ADDR_ISP + 0x5CC )
#define REG_DUMMY54                  (BASE_ADDR_ISP + 0x5D0 )
#define REG_DUMMY55                  (BASE_ADDR_ISP + 0x5D4 )
#define REG_DUMMY56                  (BASE_ADDR_ISP + 0x5D8 )
#define REG_DUMMY57                  (BASE_ADDR_ISP + 0x5DC )
#define REG_DUMMY58                  (BASE_ADDR_ISP + 0x5E0 )
#define REG_DUMMY59                  (BASE_ADDR_ISP + 0x5E4 )
#define REG_DUMMY60                  (BASE_ADDR_ISP + 0x5E8 )
#define REG_DUMMY61                  (BASE_ADDR_ISP + 0x5EC )
#define REG_DUMMY62                  (BASE_ADDR_ISP + 0x5F0 )
#define REG_DUMMY63                  (BASE_ADDR_ISP + 0x5F4 )
#define REG_DUMMY64                  (BASE_ADDR_ISP + 0x5F8 )
#define REG_DUMMY65                  (BASE_ADDR_ISP + 0x5FC )
#define REG_DUMMY66                  (BASE_ADDR_ISP + 0x600 )
#define REG_DUMMY67                  (BASE_ADDR_ISP + 0x604 )
#define REG_DUMMY68                  (BASE_ADDR_ISP + 0x608 )
#define REG_DUMMY69                  (BASE_ADDR_ISP + 0x60C )
#define REG_DUMMY70                  (BASE_ADDR_ISP + 0x610 )
#define REG_DUMMY71                  (BASE_ADDR_ISP + 0x614 )
#define REG_DUMMY72                  (BASE_ADDR_ISP + 0x618 )
#define REG_DUMMY73                  (BASE_ADDR_ISP + 0x61C )
#define REG_DUMMY74                  (BASE_ADDR_ISP + 0x620 )
#define REG_DUMMY75                  (BASE_ADDR_ISP + 0x624 )
#define REG_DUMMY76                  (BASE_ADDR_ISP + 0x628 )
#define REG_DUMMY77                  (BASE_ADDR_ISP + 0x62C )
#define REG_DUMMY78                  (BASE_ADDR_ISP + 0x630 )
#define REG_DUMMY79                  (BASE_ADDR_ISP + 0x634 )
#define REG_DUMMY80                  (BASE_ADDR_ISP + 0x638 )
#define REG_DUMMY81                  (BASE_ADDR_ISP + 0x63C )
#define REG_DUMMY82                  (BASE_ADDR_ISP + 0x640 )
#define REG_DUMMY83                  (BASE_ADDR_ISP + 0x644 )
#define REG_DUMMY84                  (BASE_ADDR_ISP + 0x648 )
#define REG_DUMMY85                  (BASE_ADDR_ISP + 0x64C )
#define REG_DUMMY86                  (BASE_ADDR_ISP + 0x650 )
#define REG_DUMMY87                  (BASE_ADDR_ISP + 0x654 )
#define REG_DUMMY88                  (BASE_ADDR_ISP + 0x658 )
#define REG_DUMMY89                  (BASE_ADDR_ISP + 0x65C )
#define REG_DUMMY90                  (BASE_ADDR_ISP + 0x660 )
#define REG_DUMMY91                  (BASE_ADDR_ISP + 0x664 )
#define REG_DUMMY92                  (BASE_ADDR_ISP + 0x668 )
#define REG_DUMMY93                  (BASE_ADDR_ISP + 0x66C )
#define REG_DUMMY94                  (BASE_ADDR_ISP + 0x670 )
#define REG_DUMMY95                  (BASE_ADDR_ISP + 0x674 )
#define REG_DUMMY96                  (BASE_ADDR_ISP + 0x678 )
#define REG_DUMMY97                  (BASE_ADDR_ISP + 0x67C )
#define REG_DUMMY98                  (BASE_ADDR_ISP + 0x680 )
#define REG_DUMMY99                  (BASE_ADDR_ISP + 0x684 )
#define REG_DUMMY100                 (BASE_ADDR_ISP + 0x688 )
#define REG_DUMMY101                 (BASE_ADDR_ISP + 0x68C )
#define REG_DUMMY102                 (BASE_ADDR_ISP + 0x690 )
#define REG_DUMMY103                 (BASE_ADDR_ISP + 0x694 )
#define REG_DUMMY104                 (BASE_ADDR_ISP + 0x698 )
#define REG_DUMMY105                 (BASE_ADDR_ISP + 0x69C )
#define REG_DUMMY106                 (BASE_ADDR_ISP + 0x6A0 )
#define REG_DUMMY107                 (BASE_ADDR_ISP + 0x6A4 )
#define REG_DUMMY108                 (BASE_ADDR_ISP + 0x6A8 )
#define REG_DUMMY109                 (BASE_ADDR_ISP + 0x6AC )
#define REG_DUMMY110                 (BASE_ADDR_ISP + 0x6B0 )
#define REG_DUMMY111                 (BASE_ADDR_ISP + 0x6B4 )
#define REG_DUMMY112                 (BASE_ADDR_ISP + 0x6B8 )
#define REG_DUMMY113                 (BASE_ADDR_ISP + 0x6BC )
#define REG_DUMMY114                 (BASE_ADDR_ISP + 0x6C0 )
#define REG_DUMMY115                 (BASE_ADDR_ISP + 0x6C4 )
#define REG_DUMMY116                 (BASE_ADDR_ISP + 0x6C8 )
#define REG_DUMMY117                 (BASE_ADDR_ISP + 0x6CC )
#define REG_DUMMY118                 (BASE_ADDR_ISP + 0x6D0 )
#define REG_DUMMY119                 (BASE_ADDR_ISP + 0x6D4 )
#define REG_DUMMY120                 (BASE_ADDR_ISP + 0x6D8 )
#define REG_DUMMY121                 (BASE_ADDR_ISP + 0x6DC )
#define REG_DUMMY122                 (BASE_ADDR_ISP + 0x6E0 )
#define REG_DUMMY123                 (BASE_ADDR_ISP + 0x6E4 )
#define REG_DUMMY124                 (BASE_ADDR_ISP + 0x6E8 )
#define REG_DUMMY125                 (BASE_ADDR_ISP + 0x6EC )
#define REG_DUMMY126                 (BASE_ADDR_ISP + 0x6F0 )
#define REG_DUMMY127                 (BASE_ADDR_ISP + 0x6F4 )
#define REG_DUMMY128                 (BASE_ADDR_ISP + 0x6F8 )
#define REG_DUMMY129                 (BASE_ADDR_ISP + 0x6FC )
#define REG_DUMMY130                 (BASE_ADDR_ISP + 0x700 )
#define REG_DUMMY131                 (BASE_ADDR_ISP + 0x704 )
#define REG_DUMMY132                 (BASE_ADDR_ISP + 0x708 )
#define REG_DUMMY133                 (BASE_ADDR_ISP + 0x70C )
#define REG_DUMMY134                 (BASE_ADDR_ISP + 0x710 )
#define REG_DUMMY135                 (BASE_ADDR_ISP + 0x714 )
#define REG_DUMMY136                 (BASE_ADDR_ISP + 0x718 )
#define REG_DUMMY137                 (BASE_ADDR_ISP + 0x71C )
#define REG_DUMMY138                 (BASE_ADDR_ISP + 0x720 )
#define REG_DUMMY139                 (BASE_ADDR_ISP + 0x724 )
#define REG_DUMMY140                 (BASE_ADDR_ISP + 0x728 )
#define REG_DUMMY141                 (BASE_ADDR_ISP + 0x72C )
#define REG_DUMMY142                 (BASE_ADDR_ISP + 0x730 )
#define REG_DUMMY143                 (BASE_ADDR_ISP + 0x734 )
#define REG_DUMMY144                 (BASE_ADDR_ISP + 0x738 )
#define REG_DUMMY145                 (BASE_ADDR_ISP + 0x73C )
#define REG_DUMMY146                 (BASE_ADDR_ISP + 0x740 )
#define REG_DUMMY147                 (BASE_ADDR_ISP + 0x744 )
#define REG_DUMMY148                 (BASE_ADDR_ISP + 0x748 )
#define REG_DUMMY149                 (BASE_ADDR_ISP + 0x74C )
#define REG_DUMMY150                 (BASE_ADDR_ISP + 0x750 )
#define REG_AUTO_CONTROL_1           (BASE_ADDR_ISP + 0x810 )
#define REG_AUTO_CONTROL_2           (BASE_ADDR_ISP + 0x814 )
#define REG_AUTO_CONTROL_3           (BASE_ADDR_ISP + 0x818 )
#define REG_AUTO_CONTROL_4           (BASE_ADDR_ISP + 0x81C )
#define REG_EXPOSURE_MODE            (BASE_ADDR_ISP + 0x820 )
#define REG_WB_MODE                  (BASE_ADDR_ISP + 0x824 )
#define REG_EXPFRMH_H                (BASE_ADDR_ISP + 0x828 )
#define REG_EXPFRMH_L                (BASE_ADDR_ISP + 0x82C )
#define REG_MIDFRMHEIGHT_H           (BASE_ADDR_ISP + 0x830 )
#define REG_MIDFRMHEIGHT_L           (BASE_ADDR_ISP + 0x834 )
#define REG_MAXFRMHEIGHT_H           (BASE_ADDR_ISP + 0x838 )
#define REG_MAXFRMHEIGHT_L           (BASE_ADDR_ISP + 0x83C )
#define REG_MINEXP_H                 (BASE_ADDR_ISP + 0x840 )
#define REG_MINEXP_M                 (BASE_ADDR_ISP + 0x844 )
#define REG_MINEXP_L                 (BASE_ADDR_ISP + 0x848 )
#define REG_MIDEXP_T                 (BASE_ADDR_ISP + 0x84C )
#define REG_MIDEXP_H                 (BASE_ADDR_ISP + 0x850 )
#define REG_MIDEXP_M                 (BASE_ADDR_ISP + 0x854 )
#define REG_MAXEXP_T                 (BASE_ADDR_ISP + 0x858 )
#define REG_MAXEXP_H                 (BASE_ADDR_ISP + 0x85C )
#define REG_MAXEXP_M                 (BASE_ADDR_ISP + 0x860 )
#define REG_IT1_H                    (BASE_ADDR_ISP + 0x864 )
#define REG_IT1_L                    (BASE_ADDR_ISP + 0x868 )
#define REG_IT2_H                    (BASE_ADDR_ISP + 0x86C )
#define REG_IT2_L                    (BASE_ADDR_ISP + 0x870 )
#define REG_GAIN1                    (BASE_ADDR_ISP + 0x874 )
#define REG_GAIN2                    (BASE_ADDR_ISP + 0x878 )
#define REG_DGAIN                    (BASE_ADDR_ISP + 0x87C )
#define REG_EXT_INTTIME_H            (BASE_ADDR_ISP + 0x880 )
#define REG_EXT_INTTIME_M            (BASE_ADDR_ISP + 0x884 )
#define REG_EXT_INTTIME_L            (BASE_ADDR_ISP + 0x888 )
#define REG_EXT_GLBG_H               (BASE_ADDR_ISP + 0x88C )
#define REG_EXT_GLBG_L               (BASE_ADDR_ISP + 0x890 )
#define REG_EXPOSURE_T               (BASE_ADDR_ISP + 0x894 )
#define REG_EXPOSURE_H               (BASE_ADDR_ISP + 0x898 )
#define REG_EXPOSURE_M               (BASE_ADDR_ISP + 0x89C )
#define REG_EXPOSURE_L               (BASE_ADDR_ISP + 0x8A0 )
#define REG_AUTO_LEDCTRL             (BASE_ADDR_ISP + 0x8A4 )
#define REG_AUTO_LEDCTRL_MODE        (BASE_ADDR_ISP + 0x8A8 )
#define REG_SRATIO_WEIGHT            (BASE_ADDR_ISP + 0x8AC )
#define REG_SRATIO                   (BASE_ADDR_ISP + 0x8B0 )
#define REG_AE_WEIGHT1               (BASE_ADDR_ISP + 0x8B4 )
#define REG_AE_WEIGHT2               (BASE_ADDR_ISP + 0x8B8 )
#define REG_AE_WEIGHT3               (BASE_ADDR_ISP + 0x8BC )
#define REG_AE_WEIGHT4               (BASE_ADDR_ISP + 0x8C0 )
#define REG_AE_WEIGHTC               (BASE_ADDR_ISP + 0x8C4 )
#define REG_YMEAN_REF0               (BASE_ADDR_ISP + 0x8C8 )
#define REG_YMEAN_REF1               (BASE_ADDR_ISP + 0x8CC )
#define REG_YMEAN_REF2               (BASE_ADDR_ISP + 0x8D0 )
#define REG_YMEAN_REF3               (BASE_ADDR_ISP + 0x8D4 )
#define REG_YMEAN_H                  (BASE_ADDR_ISP + 0x8D8 )
#define REG_YMEAN_L                  (BASE_ADDR_ISP + 0x8DC )
#define REG_MAX_YT1                  (BASE_ADDR_ISP + 0x8E0 )
#define REG_MAX_YT2                  (BASE_ADDR_ISP + 0x8E4 )
#define REG_MAX_YT3                  (BASE_ADDR_ISP + 0x8E8 )
#define REG_MIN_YT1                  (BASE_ADDR_ISP + 0x8EC )
#define REG_MIN_YT2                  (BASE_ADDR_ISP + 0x8F0 )
#define REG_MIN_YT3                  (BASE_ADDR_ISP + 0x8F4 )
#define REG_YT_XREF1_T               (BASE_ADDR_ISP + 0x8F8 )
#define REG_YT_XREF1_H               (BASE_ADDR_ISP + 0x8FC )
#define REG_YT_XREF1_M               (BASE_ADDR_ISP + 0x900 )
#define REG_YT_XREF2_T               (BASE_ADDR_ISP + 0x904 )
#define REG_YT_XREF2_H               (BASE_ADDR_ISP + 0x908 )
#define REG_YT_XREF2_M               (BASE_ADDR_ISP + 0x90C )
#define REG_YT_XREF3_T               (BASE_ADDR_ISP + 0x910 )
#define REG_YT_XREF3_H               (BASE_ADDR_ISP + 0x914 )
#define REG_YT_XREF3_M               (BASE_ADDR_ISP + 0x918 )
#define REG_YT_XREF4_T               (BASE_ADDR_ISP + 0x91C )
#define REG_YT_XREF4_H               (BASE_ADDR_ISP + 0x920 )
#define REG_YT_XREF4_M               (BASE_ADDR_ISP + 0x924 )
#define REG_SRATIO_REF0              (BASE_ADDR_ISP + 0x928 )
#define REG_SRATIO_REF1              (BASE_ADDR_ISP + 0x92C )
#define REG_SRATIO_REF2              (BASE_ADDR_ISP + 0x930 )
#define REG_SRATIO_REF3              (BASE_ADDR_ISP + 0x934 )
#define REG_YT_STEP                  (BASE_ADDR_ISP + 0x938 )
#define REG_YTARGET                  (BASE_ADDR_ISP + 0x93C )
#define REG_USER_WYT                 (BASE_ADDR_ISP + 0x940 )
#define REG_AE_UP_SPEED              (BASE_ADDR_ISP + 0x944 )
#define REG_AE_DOWN_SPEED            (BASE_ADDR_ISP + 0x948 )
#define REG_AE_LOCK                  (BASE_ADDR_ISP + 0x94C )
#define REG_AUTO_FLAG                (BASE_ADDR_ISP + 0x950 )
#define REG_AFD_TH_H                 (BASE_ADDR_ISP + 0x954 )
#define REG_AFD_TH_M                 (BASE_ADDR_ISP + 0x958 )
#define REG_RG_RATIO_A               (BASE_ADDR_ISP + 0x95C )
#define REG_BG_RATIO_A               (BASE_ADDR_ISP + 0x960 )
#define REG_RG_RATIO_B               (BASE_ADDR_ISP + 0x964 )
#define REG_BG_RATIO_B               (BASE_ADDR_ISP + 0x968 )
#define REG_RG_RATIO_C               (BASE_ADDR_ISP + 0x96C )
#define REG_BG_RATIO_C               (BASE_ADDR_ISP + 0x970 )
#define REG_RATIO_AXIS_A             (BASE_ADDR_ISP + 0x974 )
#define REG_RATIO_AXIS_B             (BASE_ADDR_ISP + 0x978 )
#define REG_RATIO_AXIS_C             (BASE_ADDR_ISP + 0x97C )
#define REG_AWB_RGRATIO              (BASE_ADDR_ISP + 0x980 )
#define REG_AWB_BGRATIO              (BASE_ADDR_ISP + 0x984 )
#define REG_AWB_LOCK                 (BASE_ADDR_ISP + 0x988 )
#define REG_AWB_SPEED                (BASE_ADDR_ISP + 0x98C )
#define REG_AWB_RGAIN_MIN            (BASE_ADDR_ISP + 0x990 )
#define REG_AWB_RGAIN_MAX            (BASE_ADDR_ISP + 0x994 )
#define REG_AWB_BGAIN_MIN            (BASE_ADDR_ISP + 0x998 )
#define REG_AWB_BGAIN_MAX_H          (BASE_ADDR_ISP + 0x99C )
#define REG_AWB_BGAIN_MAX_M          (BASE_ADDR_ISP + 0x9A0 )
#define REG_FILTER_CTRL_1            (BASE_ADDR_ISP + 0x9A4 )
#define REG_DARK_XREF0_H             (BASE_ADDR_ISP + 0x9A8 )
#define REG_DARK_XREF0_M             (BASE_ADDR_ISP + 0x9AC )
#define REG_DARK_XREF1_H             (BASE_ADDR_ISP + 0x9B0 )
#define REG_DARK_XREF1_M             (BASE_ADDR_ISP + 0x9B4 )
#define REG_DARK_XREF2_H             (BASE_ADDR_ISP + 0x9B8 )
#define REG_DARK_XREF2_M             (BASE_ADDR_ISP + 0x9BC )
#define REG_DARK_XREF3_T             (BASE_ADDR_ISP + 0x9C0 )
#define REG_DARK_XREF3_H             (BASE_ADDR_ISP + 0x9C4 )
#define REG_DARK_XREF3_M             (BASE_ADDR_ISP + 0x9C8 )
#define REG_DARK_XREF4_T             (BASE_ADDR_ISP + 0x9CC )
#define REG_DARK_XREF4_H             (BASE_ADDR_ISP + 0x9D0 )
#define REG_DARK_XREF4_M             (BASE_ADDR_ISP + 0x9D4 )
#define REG_REFGAIN_MIN              (BASE_ADDR_ISP + 0x9D8 )
#define REG_REFGAIN0                 (BASE_ADDR_ISP + 0x9DC )
#define REG_REFGAIN1                 (BASE_ADDR_ISP + 0x9E0 )
#define REG_REFGAIN2                 (BASE_ADDR_ISP + 0x9E4 )
#define REG_REFGAIN3                 (BASE_ADDR_ISP + 0x9E8 )
#define REG_REFGAIN4                 (BASE_ADDR_ISP + 0x9EC )
#define REG_RGAIN_NO_NORMAL_M        (BASE_ADDR_ISP + 0x9F0 )
#define REG_RGAIN_NO_NORMAL_L        (BASE_ADDR_ISP + 0x9F4 )
#define REG_BGAIN_NO_NORMAL_H        (BASE_ADDR_ISP + 0x9F8 )
#define REG_BGAIN_NO_NORMAL_M        (BASE_ADDR_ISP + 0x9FC )
#define REG_BGAIN_NO_NORMAL_L        (BASE_ADDR_ISP + 0xA00 )
#define REG_AWB_FULL_TH1             (BASE_ADDR_ISP + 0xA04 )
#define REG_AWB_FULL_TH2             (BASE_ADDR_ISP + 0xA08 )
#define REG_LED_MTR                  (BASE_ADDR_ISP + 0xA10 )
#define REG_AWB_NUM_BYTE2            (BASE_ADDR_ISP + 0xA14 )
#define REG_AWB_NUM_BYTE1            (BASE_ADDR_ISP + 0xA18 )
#define REG_AWB_NUM_BYTE0            (BASE_ADDR_ISP + 0xA1C )
#define REG_AWB_SUM_R_BYTE3          (BASE_ADDR_ISP + 0xA20 )
#define REG_AWB_SUM_R_BYTE2          (BASE_ADDR_ISP + 0xA24 )
#define REG_AWB_SUM_R_BYTE1          (BASE_ADDR_ISP + 0xA28 )
#define REG_AWB_SUM_R_BYTE0          (BASE_ADDR_ISP + 0xA2C )
#define REG_AWB_SUM_G_BYTE3          (BASE_ADDR_ISP + 0xA30 )
#define REG_AWB_SUM_G_BYTE2          (BASE_ADDR_ISP + 0xA34 )
#define REG_AWB_SUM_G_BYTE1          (BASE_ADDR_ISP + 0xA38 )
#define REG_AWB_SUM_G_BYTE0          (BASE_ADDR_ISP + 0xA3C )
#define REG_AWB_SUM_B_BYTE3          (BASE_ADDR_ISP + 0xA40 )
#define REG_AWB_SUM_B_BYTE2          (BASE_ADDR_ISP + 0xA44 )
#define REG_AWB_SUM_B_BYTE1          (BASE_ADDR_ISP + 0xA48 )
#define REG_AWB_SUM_B_BYTE0          (BASE_ADDR_ISP + 0xA4C )
#define REG_NUM_SAMPLE1_BYTE2        (BASE_ADDR_ISP + 0xA50 )
#define REG_NUM_SAMPLE1_BYTE1        (BASE_ADDR_ISP + 0xA54 )
#define REG_NUM_SAMPLE1_BYTE0        (BASE_ADDR_ISP + 0xA58 )
#define REG_NUM_SAMPLE2_BYTE2        (BASE_ADDR_ISP + 0xA5C )
#define REG_NUM_SAMPLE2_BYTE1        (BASE_ADDR_ISP + 0xA60 )
#define REG_NUM_SAMPLE2_BYTE0        (BASE_ADDR_ISP + 0xA64 )
#define REG_NUM_SAMPLE3_BYTE2        (BASE_ADDR_ISP + 0xA68 )
#define REG_NUM_SAMPLE3_BYTE1        (BASE_ADDR_ISP + 0xA6C )
#define REG_NUM_SAMPLE3_BYTE0        (BASE_ADDR_ISP + 0xA70 )
#define REG_NUM_SAMPLE4_BYTE2        (BASE_ADDR_ISP + 0xA74 )
#define REG_NUM_SAMPLE4_BYTE1        (BASE_ADDR_ISP + 0xA78 )
#define REG_NUM_SAMPLE4_BYTE0        (BASE_ADDR_ISP + 0xA7C )
#define REG_NUM_SAMPLEC_BYTE2        (BASE_ADDR_ISP + 0xA80 )
#define REG_NUM_SAMPLEC_BYTE1        (BASE_ADDR_ISP + 0xA84 )
#define REG_NUM_SAMPLEC_BYTE0        (BASE_ADDR_ISP + 0xA88 )
#define REG_NUM_SAT_CENTER_BYTE2     (BASE_ADDR_ISP + 0xA8C )
#define REG_NUM_SAT_CENTER_BYTE1     (BASE_ADDR_ISP + 0xA90 )
#define REG_NUM_SAT_CENTER_BYTE0     (BASE_ADDR_ISP + 0xA94 )
#define REG_NUM_SAT_PERI_BYTE2       (BASE_ADDR_ISP + 0xA98 )
#define REG_NUM_SAT_PERI_BYTE1       (BASE_ADDR_ISP + 0xA9C )
#define REG_NUM_SAT_PERI_BYTE0       (BASE_ADDR_ISP + 0xAA0 )
#define REG_SUM_SAMPLE1_BYTE3        (BASE_ADDR_ISP + 0xAA4 )
#define REG_SUM_SAMPLE1_BYTE2        (BASE_ADDR_ISP + 0xAA8 )
#define REG_SUM_SAMPLE1_BYTE1        (BASE_ADDR_ISP + 0xAAC )
#define REG_SUM_SAMPLE1_BYTE0        (BASE_ADDR_ISP + 0xAB0 )
#define REG_SUM_SAMPLE2_BYTE3        (BASE_ADDR_ISP + 0xAB4 )
#define REG_SUM_SAMPLE2_BYTE2        (BASE_ADDR_ISP + 0xAB8 )
#define REG_SUM_SAMPLE2_BYTE1        (BASE_ADDR_ISP + 0xABC )
#define REG_SUM_SAMPLE2_BYTE0        (BASE_ADDR_ISP + 0xAC0 )
#define REG_SUM_SAMPLE3_BYTE3        (BASE_ADDR_ISP + 0xAC4 )
#define REG_SUM_SAMPLE3_BYTE2        (BASE_ADDR_ISP + 0xAC8 )
#define REG_SUM_SAMPLE3_BYTE1        (BASE_ADDR_ISP + 0xACC )
#define REG_SUM_SAMPLE3_BYTE0        (BASE_ADDR_ISP + 0xAD0 )
#define REG_SUM_SAMPLE4_BYTE3        (BASE_ADDR_ISP + 0xAD4 )
#define REG_SUM_SAMPLE4_BYTE2        (BASE_ADDR_ISP + 0xAD8 )
#define REG_SUM_SAMPLE4_BYTE1        (BASE_ADDR_ISP + 0xADC )
#define REG_SUM_SAMPLE4_BYTE0        (BASE_ADDR_ISP + 0xAE0 )
#define REG_SUM_SAMPLEC_BYTE3        (BASE_ADDR_ISP + 0xAE4 )
#define REG_SUM_SAMPLEC_BYTE2        (BASE_ADDR_ISP + 0xAE8 )
#define REG_SUM_SAMPLEC_BYTE1        (BASE_ADDR_ISP + 0xAEC )
#define REG_SUM_SAMPLEC_BYTE0        (BASE_ADDR_ISP + 0xAF0 )
#define REG_AUTO_FCNT                (BASE_ADDR_ISP + 0xAF4 )
#define REG_AVG_R                    (BASE_ADDR_ISP + 0xAFC )
#define REG_AVG_G                    (BASE_ADDR_ISP + 0xB00 )
#define REG_AVG_B                    (BASE_ADDR_ISP + 0xB04 )
#define REG_SFT_R                    (BASE_ADDR_ISP + 0xB08 )
#define REG_SFT_G                    (BASE_ADDR_ISP + 0xB0C )
#define REG_SFT_B                    (BASE_ADDR_ISP + 0xB10 )
#define REG_LED_C_SUM3               (BASE_ADDR_ISP + 0xB18 )
#define REG_LED_C_SUM2               (BASE_ADDR_ISP + 0xB1C )
#define REG_LED_C_SUM1               (BASE_ADDR_ISP + 0xB20 )
#define REG_LED_C_SUM0               (BASE_ADDR_ISP + 0xB24 )
#define REG_MONITOR_STARGET          (BASE_ADDR_ISP + 0xB28 )
#define REG_MIRROR                   (BASE_ADDR_ISP + 0xC10 )
#define REG_FRAMEWIDTH_H             (BASE_ADDR_ISP + 0xC14 )
#define REG_FRAMEWIDTH_L             (BASE_ADDR_ISP + 0xC18 )
#define REG_FD_FHEIGHT_A_H           (BASE_ADDR_ISP + 0xC24 )
#define REG_FD_FHEIGHT_A_L           (BASE_ADDR_ISP + 0xC28 )
#define REG_FD_FHEIGHT_B_H           (BASE_ADDR_ISP + 0xC2C )
#define REG_FD_FHEIGHT_B_L           (BASE_ADDR_ISP + 0xC30 )
#define REG_BAYER_WIDTH_H            (BASE_ADDR_ISP + 0xC38 )
#define REG_BAYER_WIDTH_L            (BASE_ADDR_ISP + 0xC3C )
#define REG_BAYER_HEIGHT_H           (BASE_ADDR_ISP + 0xC40 )
#define REG_BAYER_HEIGHT_L           (BASE_ADDR_ISP + 0xC44 )
#define REG_RCOUNT_INIT_H            (BASE_ADDR_ISP + 0xC48 )
#define REG_RCOUNT_INIT_L            (BASE_ADDR_ISP + 0xC4C )
#define REG_CCOUNT_INIT_H            (BASE_ADDR_ISP + 0xC50 )
#define REG_CCOUNT_INIT_L            (BASE_ADDR_ISP + 0xC54 )
#define REG_MONITOR                  (BASE_ADDR_ISP + 0xC58 )
#define REG_FD_A_STEP_H              (BASE_ADDR_ISP + 0xC5C )
#define REG_FD_A_STEP_L              (BASE_ADDR_ISP + 0xC60 )
#define REG_FD_B_STEP_H              (BASE_ADDR_ISP + 0xC64 )
#define REG_FD_B_STEP_L              (BASE_ADDR_ISP + 0xC68 )
#define REG_FD_WINHEIGHT             (BASE_ADDR_ISP + 0xC6C )
#define REG_FD_A_DELAY               (BASE_ADDR_ISP + 0xC70 )
#define REG_FD_B_DELAY               (BASE_ADDR_ISP + 0xC74 )
#define REG_FD_TH                    (BASE_ADDR_ISP + 0xC78 )
#define REG_FD_PERIOD_H              (BASE_ADDR_ISP + 0xC7C )
#define REG_FD_PERIOD_M              (BASE_ADDR_ISP + 0xC80 )
#define REG_FD_PERIOD_L              (BASE_ADDR_ISP + 0xC84 )
#define REG_FD_FHEIGHT_H             (BASE_ADDR_ISP + 0xC88 )
#define REG_FD_FHEIGHT_L             (BASE_ADDR_ISP + 0xC8C )
#define REG_AE_HISTO_CTRL            (BASE_ADDR_ISP + 0xC94 )
#define REG_AE_HISTO_NTH             (BASE_ADDR_ISP + 0xC98 )
#define REG_AE_HISTO_MTH             (BASE_ADDR_ISP + 0xC9C )
#define REG_AE_HISTO_YTH             (BASE_ADDR_ISP + 0xCA0 )
#define REG_AE_YSAT                  (BASE_ADDR_ISP + 0xCA8 )
#define REG_AWB_CTRL                 (BASE_ADDR_ISP + 0xCAC )
#define REG_AWB_SIZE                 (BASE_ADDR_ISP + 0xCB0 )
#define REG_AWB_MAXC                 (BASE_ADDR_ISP + 0xCB4 )
#define REG_AWB_MINC                 (BASE_ADDR_ISP + 0xCB8 )
#define REG_AWB_REDP                 (BASE_ADDR_ISP + 0xCBC )
#define REG_AWB_GTH                  (BASE_ADDR_ISP + 0xCC0 )
#define REG_AWB_NTH_H                (BASE_ADDR_ISP + 0xCC4 )
#define REG_AWB_NTH_L                (BASE_ADDR_ISP + 0xCC8 )
#define REG_AWB_ATH                  (BASE_ADDR_ISP + 0xCCC )
#define REG_AWB_IRED                 (BASE_ADDR_ISP + 0xCD0 )
#define REG_AWB_IBLU                 (BASE_ADDR_ISP + 0xCD4 )
#define REG_AWB_RMIN1                (BASE_ADDR_ISP + 0xCD8 )
#define REG_AWB_RMAX1                (BASE_ADDR_ISP + 0xCDC )
#define REG_AWB_BMIN1                (BASE_ADDR_ISP + 0xCE0 )
#define REG_AWB_BMAX1_H              (BASE_ADDR_ISP + 0xCE4 )
#define REG_AWB_BMAX1_L              (BASE_ADDR_ISP + 0xCE8 )
#define REG_AWB_DBUP1                (BASE_ADDR_ISP + 0xCEC )
#define REG_AWB_DBLW1                (BASE_ADDR_ISP + 0xCF0 )
#define REG_AWB_RMIN2                (BASE_ADDR_ISP + 0xCF4 )
#define REG_AWB_RMAX2                (BASE_ADDR_ISP + 0xCF8 )
#define REG_AWB_BMIN2                (BASE_ADDR_ISP + 0xCFC )
#define REG_AWB_BMAX2                (BASE_ADDR_ISP + 0xD00 )
#define REG_AWB_DBUP2                (BASE_ADDR_ISP + 0xD04 )
#define REG_AWB_DBLW2                (BASE_ADDR_ISP + 0xD08 )
#define REG_I2C_CONTROL_1            (BASE_ADDR_ISP + 0xD10 )
#define REG_INTERRUPT_CTRL           (BASE_ADDR_ISP + 0xD14 )
#define REG_INTERRUPT_PW             (BASE_ADDR_ISP + 0xD18 )
#define REG_INTERRUPT_ROW1_H         (BASE_ADDR_ISP + 0xD1C )
#define REG_INTERRUPT_ROW1_L         (BASE_ADDR_ISP + 0xD20 )
#define REG_INTERRUPT_ROW2_H         (BASE_ADDR_ISP + 0xD24 )
#define REG_INTERRUPT_ROW2_L         (BASE_ADDR_ISP + 0xD28 )
#define REG_INTERRUPT_ROW3_H         (BASE_ADDR_ISP + 0xD2C )
#define REG_INTERRUPT_ROW3_L         (BASE_ADDR_ISP + 0xD30 )
#define REG_TOTALGAIN_H              (BASE_ADDR_ISP + 0xD38 )
#define REG_TOTALGAIN_L              (BASE_ADDR_ISP + 0xD3C )
#define REG_INV_RGAIN                (BASE_ADDR_ISP + 0xD40 )
#define REG_INV_GGAIN                (BASE_ADDR_ISP + 0xD44 )
#define REG_INV_BGAIN                (BASE_ADDR_ISP + 0xD48 )
#define REG_AWB_FULL                 (BASE_ADDR_ISP + 0xD4C )
#define REG_FLICKER_CONTROL1         (BASE_ADDR_ISP + 0xD54 )
#define REG_AUTO_FD                  (BASE_ADDR_ISP + 0xD58 )
#define REG_FD_PERIOD_A_H            (BASE_ADDR_ISP + 0xD5C )
#define REG_FD_PERIOD_A_M            (BASE_ADDR_ISP + 0xD60 )
#define REG_FD_PERIOD_A_L            (BASE_ADDR_ISP + 0xD64 )
#define REG_FD_PERIOD_B_H            (BASE_ADDR_ISP + 0xD68 )
#define REG_FD_PERIOD_B_M            (BASE_ADDR_ISP + 0xD6C )
#define REG_FD_PERIOD_B_L            (BASE_ADDR_ISP + 0xD70 )
#define REG_FD_STATE                 (BASE_ADDR_ISP + 0xD74 )
#define REG_ISP_FUNC_0               (BASE_ADDR_ISP + 0xD98 )
#define REG_ISP_FUNC_1               (BASE_ADDR_ISP + 0xD9C )
#define REG_ISP_FUNC_2               (BASE_ADDR_ISP + 0xDA0 )
#define REG_ISP_FUNC_3               (BASE_ADDR_ISP + 0xDA4 )
#define REG_ISP_FUNC_4               (BASE_ADDR_ISP + 0xDA8 )
#define REG_ISP_FUNC_5               (BASE_ADDR_ISP + 0xDAC )
#define REG_ISP_FUNC_6               (BASE_ADDR_ISP + 0xDB0 )
#define REG_ISP_FUNC_7               (BASE_ADDR_ISP + 0xDB4 )
#define REG_ISP_FUNC_8               (BASE_ADDR_ISP + 0xDB8 )
#define REG_TP_CONTROL_0             (BASE_ADDR_ISP + 0xDC0 )
#define REG_TP_CONTROL_1             (BASE_ADDR_ISP + 0xDC4 )
#define REG_TP_CONTROL_2             (BASE_ADDR_ISP + 0xDC8 )
#define REG_TP_CONTROL_3             (BASE_ADDR_ISP + 0xDCC )
#define REG_TP_CONTROL_4             (BASE_ADDR_ISP + 0xDD0 )
#define REG_TP_CONTROL_5             (BASE_ADDR_ISP + 0xDD4 )
#define REG_TP_WIDTH_H               (BASE_ADDR_ISP + 0xDD8 )
#define REG_TP_WIDTH_L               (BASE_ADDR_ISP + 0xDDC )
#define REG_BLC_CTRL                 (BASE_ADDR_ISP + 0xDE4 )
#define REG_FB_R                     (BASE_ADDR_ISP + 0xDE8 )
#define REG_FB_GR                    (BASE_ADDR_ISP + 0xDEC )
#define REG_FB_GB                    (BASE_ADDR_ISP + 0xDF0 )
#define REG_FB_B                     (BASE_ADDR_ISP + 0xDF4 )
#define REG_PEDESTAL_R               (BASE_ADDR_ISP + 0xDF8 )
#define REG_PEDESTAL_GR              (BASE_ADDR_ISP + 0xDFC )
#define REG_PEDESTAL_GB              (BASE_ADDR_ISP + 0xE00 )
#define REG_PEDESTAL_B               (BASE_ADDR_ISP + 0xE04 )
#define REG_LENS_SCALE               (BASE_ADDR_ISP + 0xE0C )
#define REG_LENS_X                   (BASE_ADDR_ISP + 0xE10 )
#define REG_LENS_Y                   (BASE_ADDR_ISP + 0xE14 )
#define REG_LENS_GAINR               (BASE_ADDR_ISP + 0xE18 )
#define REG_LENS_GAING1              (BASE_ADDR_ISP + 0xE1C )
#define REG_LENS_GAING2              (BASE_ADDR_ISP + 0xE20 )
#define REG_LENS_GAINB               (BASE_ADDR_ISP + 0xE24 )
#define REG_DPC_OFFSET               (BASE_ADDR_ISP + 0xE2C )
#define REG_DARK_DPC_P               (BASE_ADDR_ISP + 0xE30 )
#define REG_DARK_DPC_N               (BASE_ADDR_ISP + 0xE34 )
#define REG_WB_RGAIN_H               (BASE_ADDR_ISP + 0xE3C )
#define REG_WB_RGAIN_L               (BASE_ADDR_ISP + 0xE40 )
#define REG_WB_GGAIN_H               (BASE_ADDR_ISP + 0xE44 )
#define REG_WB_GGAIN_L               (BASE_ADDR_ISP + 0xE48 )
#define REG_WB_BGAIN_H               (BASE_ADDR_ISP + 0xE4C )
#define REG_WB_BGAIN_L               (BASE_ADDR_ISP + 0xE50 )
#define REG_WB_GRATIO                (BASE_ADDR_ISP + 0xE54 )
#define REG_WB_MRGAIN_H              (BASE_ADDR_ISP + 0xE58 )
#define REG_WB_MRGAIN_L              (BASE_ADDR_ISP + 0xE5C )
#define REG_WB_MGGAIN_H              (BASE_ADDR_ISP + 0xE60 )
#define REG_WB_MGGAIN_L              (BASE_ADDR_ISP + 0xE64 )
#define REG_WB_MBGAIN_H              (BASE_ADDR_ISP + 0xE68 )
#define REG_WB_MBGAIN_L              (BASE_ADDR_ISP + 0xE6C )
#define REG_WB_MANUAL                (BASE_ADDR_ISP + 0xE70 )
#define REG_BLF_CTRL                 (BASE_ADDR_ISP + 0xE78 )
#define REG_BLF_W0                   (BASE_ADDR_ISP + 0xE7C )
#define REG_BLF_X0                   (BASE_ADDR_ISP + 0xE80 )
#define REG_BLF_SLOPE                (BASE_ADDR_ISP + 0xE84 )
#define REG_DARK_BLF                 (BASE_ADDR_ISP + 0xE88 )
#define REG_DARK_NF                  (BASE_ADDR_ISP + 0xE8C )
#define REG_DEM_CTRL                 (BASE_ADDR_ISP + 0xE94 )
#define REG_CLIP_H                   (BASE_ADDR_ISP + 0xE98 )
#define REG_CLIP_L                   (BASE_ADDR_ISP + 0xE9C )
#define REG_GGOFS                    (BASE_ADDR_ISP + 0xEA0 )
#define REG_FCMSCL                   (BASE_ADDR_ISP + 0xEA4 )
#define REG_FCHSCL                   (BASE_ADDR_ISP + 0xEA8 )
#define REG_EDGETH                   (BASE_ADDR_ISP + 0xEAC )
#define REG_YMCOR                    (BASE_ADDR_ISP + 0xEB0 )
#define REG_YHCOR                    (BASE_ADDR_ISP + 0xEB4 )
#define REG_YMGAIN                   (BASE_ADDR_ISP + 0xEB8 )
#define REG_YHGAIN                   (BASE_ADDR_ISP + 0xEBC )
#define REG_E_CGM1_Y0                (BASE_ADDR_ISP + 0xEC4 )
#define REG_E_CGM1_Y1                (BASE_ADDR_ISP + 0xEC8 )
#define REG_E_CGM1_Y2                (BASE_ADDR_ISP + 0xECC )
#define REG_E_CGM1_Y3                (BASE_ADDR_ISP + 0xED0 )
#define REG_E_CGM1_Y4                (BASE_ADDR_ISP + 0xED4 )
#define REG_E_CGM1_Y5                (BASE_ADDR_ISP + 0xED8 )
#define REG_E_CGM1_Y6                (BASE_ADDR_ISP + 0xEDC )
#define REG_E_CGM1_Y7                (BASE_ADDR_ISP + 0xEE0 )
#define REG_E_CGM1_Y8                (BASE_ADDR_ISP + 0xEE4 )
#define REG_E_CGM1_Y9                (BASE_ADDR_ISP + 0xEE8 )
#define REG_E_CGM1_Y10               (BASE_ADDR_ISP + 0xEEC )
#define REG_E_CGM1_Y11               (BASE_ADDR_ISP + 0xEF0 )
#define REG_E_CGM1_Y12               (BASE_ADDR_ISP + 0xEF4 )
#define REG_E_CGM1_Y13               (BASE_ADDR_ISP + 0xEF8 )
#define REG_E_CGM1_Y14               (BASE_ADDR_ISP + 0xEFC )
#define REG_E_CGM2_Y0                (BASE_ADDR_ISP + 0xF00 )
#define REG_E_CGM2_Y1                (BASE_ADDR_ISP + 0xF04 )
#define REG_E_CGM2_Y2                (BASE_ADDR_ISP + 0xF08 )
#define REG_E_CGM2_Y3                (BASE_ADDR_ISP + 0xF0C )
#define REG_E_CGM2_Y4                (BASE_ADDR_ISP + 0xF10 )
#define REG_E_CGM2_Y5                (BASE_ADDR_ISP + 0xF14 )
#define REG_E_CGM2_Y6                (BASE_ADDR_ISP + 0xF18 )
#define REG_E_CGM2_Y7                (BASE_ADDR_ISP + 0xF1C )
#define REG_E_CGM2_Y8                (BASE_ADDR_ISP + 0xF20 )
#define REG_E_CGM2_Y9                (BASE_ADDR_ISP + 0xF24 )
#define REG_E_CGM2_Y10               (BASE_ADDR_ISP + 0xF28 )
#define REG_E_CGM2_Y11               (BASE_ADDR_ISP + 0xF2C )
#define REG_E_CGM2_Y12               (BASE_ADDR_ISP + 0xF30 )
#define REG_E_CGM2_Y13               (BASE_ADDR_ISP + 0xF34 )
#define REG_E_CGM2_Y14               (BASE_ADDR_ISP + 0xF38 )
#define REG_DARK_E_RGB_GM            (BASE_ADDR_ISP + 0xF3C )
#define REG_EGM_Y0                   (BASE_ADDR_ISP + 0xF40 )
#define REG_EGM_Y1                   (BASE_ADDR_ISP + 0xF44 )
#define REG_EGM_Y2                   (BASE_ADDR_ISP + 0xF48 )
#define REG_EGM_Y3                   (BASE_ADDR_ISP + 0xF4C )
#define REG_EGM_Y4                   (BASE_ADDR_ISP + 0xF50 )
#define REG_EGM_Y5                   (BASE_ADDR_ISP + 0xF54 )
#define REG_EGM_Y6                   (BASE_ADDR_ISP + 0xF58 )
#define REG_DARK_E_GM                (BASE_ADDR_ISP + 0xF5C )
#define REG_DARK_GAUS_K0             (BASE_ADDR_ISP + 0xF60 )
#define REG_EDGE_GAUS_K1             (BASE_ADDR_ISP + 0xF64 )
#define REG_EDGE_GAUS_K2             (BASE_ADDR_ISP + 0xF68 )
#define REG_EDGE_GAUS_K3             (BASE_ADDR_ISP + 0xF6C )
#define REG_EDGE_GAUS_K4             (BASE_ADDR_ISP + 0xF70 )
#define REG_EDGE_GAUS_K5             (BASE_ADDR_ISP + 0xF74 )
#define REG_EDGE_PGAIN               (BASE_ADDR_ISP + 0xF78 )
#define REG_EDGE_MGAIN               (BASE_ADDR_ISP + 0xF7C )
#define REG_DARK_EC_PTH              (BASE_ADDR_ISP + 0xF80 )
#define REG_DARK_EC_MTH              (BASE_ADDR_ISP + 0xF84 )
#define REG_DARK_EC_PMAX             (BASE_ADDR_ISP + 0xF88 )
#define REG_DARK_EC_MMAX             (BASE_ADDR_ISP + 0xF8C )
#define REG_EDGE_LFR                 (BASE_ADDR_ISP + 0xF90 )
#define REG_EDGE_COR_SEL             (BASE_ADDR_ISP + 0xF94 )
#define REG_DARK_HR_TH               (BASE_ADDR_ISP + 0xF98 )
#define REG_WB_ATTEN                 (BASE_ADDR_ISP + 0xFA0 )
#define REG_ISP_DGAIN_H              (BASE_ADDR_ISP + 0xFA4 )
#define REG_ISP_DGAIN_L              (BASE_ADDR_ISP + 0xFA8 )
#define REG_YGM1_Y0                  (BASE_ADDR_ISP + 0x1010)
#define REG_YGM1_Y1                  (BASE_ADDR_ISP + 0x1014)
#define REG_YGM1_Y2                  (BASE_ADDR_ISP + 0x1018)
#define REG_YGM1_Y3                  (BASE_ADDR_ISP + 0x101C)
#define REG_YGM1_Y4                  (BASE_ADDR_ISP + 0x1020)
#define REG_YGM1_Y5                  (BASE_ADDR_ISP + 0x1024)
#define REG_YGM1_Y6                  (BASE_ADDR_ISP + 0x1028)
#define REG_YGM1_Y7                  (BASE_ADDR_ISP + 0x102C)
#define REG_YGM1_Y8                  (BASE_ADDR_ISP + 0x1030)
#define REG_YGM1_Y9                  (BASE_ADDR_ISP + 0x1034)
#define REG_YGM1_Y10                 (BASE_ADDR_ISP + 0x1038)
#define REG_YGM1_Y11                 (BASE_ADDR_ISP + 0x103C)
#define REG_YGM1_Y12                 (BASE_ADDR_ISP + 0x1040)
#define REG_YGM1_Y13                 (BASE_ADDR_ISP + 0x1044)
#define REG_YGM1_Y14                 (BASE_ADDR_ISP + 0x1048)
#define REG_YGM1_Y15                 (BASE_ADDR_ISP + 0x104C)
#define REG_YGM1_Y16                 (BASE_ADDR_ISP + 0x1050)
#define REG_YGM1_Y17                 (BASE_ADDR_ISP + 0x1054)
#define REG_YGM1_Y18                 (BASE_ADDR_ISP + 0x1058)
#define REG_YGM1_Y19                 (BASE_ADDR_ISP + 0x105C)
#define REG_YGM1_Y20                 (BASE_ADDR_ISP + 0x1060)
#define REG_YGM2_Y0                  (BASE_ADDR_ISP + 0x1064)
#define REG_YGM2_Y1                  (BASE_ADDR_ISP + 0x1068)
#define REG_YGM2_Y2                  (BASE_ADDR_ISP + 0x106C)
#define REG_YGM2_Y3                  (BASE_ADDR_ISP + 0x1070)
#define REG_YGM2_Y4                  (BASE_ADDR_ISP + 0x1074)
#define REG_YGM2_Y5                  (BASE_ADDR_ISP + 0x1078)
#define REG_YGM2_Y6                  (BASE_ADDR_ISP + 0x107C)
#define REG_YGM2_Y7                  (BASE_ADDR_ISP + 0x1080)
#define REG_YGM2_Y8                  (BASE_ADDR_ISP + 0x1084)
#define REG_YGM2_Y9                  (BASE_ADDR_ISP + 0x1088)
#define REG_YGM2_Y10                 (BASE_ADDR_ISP + 0x108C)
#define REG_YGM2_Y11                 (BASE_ADDR_ISP + 0x1090)
#define REG_YGM2_Y12                 (BASE_ADDR_ISP + 0x1094)
#define REG_YGM2_Y13                 (BASE_ADDR_ISP + 0x1098)
#define REG_YGM2_Y14                 (BASE_ADDR_ISP + 0x109C)
#define REG_YGM2_Y15                 (BASE_ADDR_ISP + 0x10A0)
#define REG_YGM2_Y16                 (BASE_ADDR_ISP + 0x10A4)
#define REG_YGM2_Y17                 (BASE_ADDR_ISP + 0x10A8)
#define REG_YGM2_Y18                 (BASE_ADDR_ISP + 0x10AC)
#define REG_YGM2_Y19                 (BASE_ADDR_ISP + 0x10B0)
#define REG_YGM2_Y20                 (BASE_ADDR_ISP + 0x10B4)
#define REG_DARK_Y_GM                (BASE_ADDR_ISP + 0x10B8)
#define REG_CCR_HR_WT                (BASE_ADDR_ISP + 0x10C0)
#define REG_CCR_M11                  (BASE_ADDR_ISP + 0x10C4)
#define REG_CCR_M12                  (BASE_ADDR_ISP + 0x10C8)
#define REG_CCR_M13                  (BASE_ADDR_ISP + 0x10CC)
#define REG_CCR_M21                  (BASE_ADDR_ISP + 0x10D0)
#define REG_CCR_M22                  (BASE_ADDR_ISP + 0x10D4)
#define REG_CCR_M23                  (BASE_ADDR_ISP + 0x10D8)
#define REG_CCR_M31                  (BASE_ADDR_ISP + 0x10DC)
#define REG_CCR_M32                  (BASE_ADDR_ISP + 0x10E0)
#define REG_CCR_M33                  (BASE_ADDR_ISP + 0x10E4)
#define REG_DARK_CCR                 (BASE_ADDR_ISP + 0x10E8)
#define REG_CGM1_Y0                  (BASE_ADDR_ISP + 0x10F0)
#define REG_CGM1_Y1                  (BASE_ADDR_ISP + 0x10F4)
#define REG_CGM1_Y2                  (BASE_ADDR_ISP + 0x10F8)
#define REG_CGM1_Y3                  (BASE_ADDR_ISP + 0x10FC)
#define REG_CGM1_Y4                  (BASE_ADDR_ISP + 0x1100)
#define REG_CGM1_Y5                  (BASE_ADDR_ISP + 0x1104)
#define REG_CGM1_Y6                  (BASE_ADDR_ISP + 0x1108)
#define REG_CGM1_Y7                  (BASE_ADDR_ISP + 0x110C)
#define REG_CGM1_Y8                  (BASE_ADDR_ISP + 0x1110)
#define REG_CGM1_Y9                  (BASE_ADDR_ISP + 0x1114)
#define REG_CGM1_Y10                 (BASE_ADDR_ISP + 0x1118)
#define REG_CGM1_Y11                 (BASE_ADDR_ISP + 0x111C)
#define REG_CGM1_Y12                 (BASE_ADDR_ISP + 0x1120)
#define REG_CGM1_Y13                 (BASE_ADDR_ISP + 0x1124)
#define REG_CGM1_Y14                 (BASE_ADDR_ISP + 0x1128)
#define REG_CGM1_Y15                 (BASE_ADDR_ISP + 0x112C)
#define REG_CGM1_Y16                 (BASE_ADDR_ISP + 0x1130)
#define REG_CGM1_Y17                 (BASE_ADDR_ISP + 0x1134)
#define REG_CGM1_Y18                 (BASE_ADDR_ISP + 0x1138)
#define REG_CGM1_Y19                 (BASE_ADDR_ISP + 0x113C)
#define REG_CGM1_Y20                 (BASE_ADDR_ISP + 0x1140)
#define REG_CGM2_Y0                  (BASE_ADDR_ISP + 0x1144)
#define REG_CGM2_Y1                  (BASE_ADDR_ISP + 0x1148)
#define REG_CGM2_Y2                  (BASE_ADDR_ISP + 0x114C)
#define REG_CGM2_Y3                  (BASE_ADDR_ISP + 0x1150)
#define REG_CGM2_Y4                  (BASE_ADDR_ISP + 0x1154)
#define REG_CGM2_Y5                  (BASE_ADDR_ISP + 0x1158)
#define REG_CGM2_Y6                  (BASE_ADDR_ISP + 0x115C)
#define REG_CGM2_Y7                  (BASE_ADDR_ISP + 0x1160)
#define REG_CGM2_Y8                  (BASE_ADDR_ISP + 0x1164)
#define REG_CGM2_Y9                  (BASE_ADDR_ISP + 0x1168)
#define REG_CGM2_Y10                 (BASE_ADDR_ISP + 0x116C)
#define REG_CGM2_Y11                 (BASE_ADDR_ISP + 0x1170)
#define REG_CGM2_Y12                 (BASE_ADDR_ISP + 0x1174)
#define REG_CGM2_Y13                 (BASE_ADDR_ISP + 0x1178)
#define REG_CGM2_Y14                 (BASE_ADDR_ISP + 0x117C)
#define REG_CGM2_Y15                 (BASE_ADDR_ISP + 0x1180)
#define REG_CGM2_Y16                 (BASE_ADDR_ISP + 0x1184)
#define REG_CGM2_Y17                 (BASE_ADDR_ISP + 0x1188)
#define REG_CGM2_Y18                 (BASE_ADDR_ISP + 0x118C)
#define REG_CGM2_Y19                 (BASE_ADDR_ISP + 0x1190)
#define REG_CGM2_Y20                 (BASE_ADDR_ISP + 0x1194)
#define REG_DARK_RGB_GM              (BASE_ADDR_ISP + 0x1198)
#define REG_CBASE_HR_WT              (BASE_ADDR_ISP + 0x11A0)
#define REG_Y_WEIGHT                 (BASE_ADDR_ISP + 0x11A4)
#define REG_DARK_DC                  (BASE_ADDR_ISP + 0x11AC)
#define REG_DARK_DC_Y1               (BASE_ADDR_ISP + 0x11B0)
#define REG_DC_Y2                    (BASE_ADDR_ISP + 0x11B4)
#define REG_Y_MAX                    (BASE_ADDR_ISP + 0x11BC)
#define REG_Y_MIN                    (BASE_ADDR_ISP + 0x11C0)
#define REG_BW_TH                    (BASE_ADDR_ISP + 0x11C4)
#define REG_YBRIGHTNESS              (BASE_ADDR_ISP + 0x11C8)
#define REG_Y_CONT_TH2               (BASE_ADDR_ISP + 0x11CC)
#define REG_Y_CONT_SLOPE2            (BASE_ADDR_ISP + 0x11D0)
#define REG_CS11                     (BASE_ADDR_ISP + 0x11D8)
#define REG_CS12                     (BASE_ADDR_ISP + 0x11DC)
#define REG_CS21                     (BASE_ADDR_ISP + 0x11E0)
#define REG_CS22                     (BASE_ADDR_ISP + 0x11E4)
#define REG_USER_CS                  (BASE_ADDR_ISP + 0x11E8)
#define REG_SKIN_CONTROL             (BASE_ADDR_ISP + 0x11F0)
#define REG_SKIN_SMPLY               (BASE_ADDR_ISP + 0x11F4)
#define REG_SKIN_BTOP                (BASE_ADDR_ISP + 0x11F8)
#define REG_SKIN_RBOT                (BASE_ADDR_ISP + 0x11FC)
#define REG_SKIN_RTOP                (BASE_ADDR_ISP + 0x1200)
#define REG_SKIN_PHI                 (BASE_ADDR_ISP + 0x1204)
#define REG_SKIN_TARGET              (BASE_ADDR_ISP + 0x1208)
#define REG_VEC_EN                   (BASE_ADDR_ISP + 0x1210)
#define REG_VEC_F0                   (BASE_ADDR_ISP + 0x1214)
#define REG_VEC_T0                   (BASE_ADDR_ISP + 0x1218)
#define REG_VEC_H0                   (BASE_ADDR_ISP + 0x121C)
#define REG_VEC_S0                   (BASE_ADDR_ISP + 0x1220)
#define REG_VEC_F1                   (BASE_ADDR_ISP + 0x1224)
#define REG_VEC_T1                   (BASE_ADDR_ISP + 0x1228)
#define REG_VEC_H1                   (BASE_ADDR_ISP + 0x122C)
#define REG_VEC_S1                   (BASE_ADDR_ISP + 0x1230)
#define REG_VEC_F2                   (BASE_ADDR_ISP + 0x1234)
#define REG_VEC_T2                   (BASE_ADDR_ISP + 0x1238)
#define REG_VEC_H2                   (BASE_ADDR_ISP + 0x123C)
#define REG_VEC_S2                   (BASE_ADDR_ISP + 0x1240)
#define REG_VEC_F3                   (BASE_ADDR_ISP + 0x1244)
#define REG_VEC_T3                   (BASE_ADDR_ISP + 0x1248)
#define REG_VEC_H3                   (BASE_ADDR_ISP + 0x124C)
#define REG_VEC_S3                   (BASE_ADDR_ISP + 0x1250)
#define REG_VEC_F4                   (BASE_ADDR_ISP + 0x1254)
#define REG_VEC_T4                   (BASE_ADDR_ISP + 0x1258)
#define REG_VEC_H4                   (BASE_ADDR_ISP + 0x125C)
#define REG_VEC_S4                   (BASE_ADDR_ISP + 0x1260)
#define REG_VEC_F5                   (BASE_ADDR_ISP + 0x1264)
#define REG_VEC_T5                   (BASE_ADDR_ISP + 0x1268)
#define REG_VEC_H5                   (BASE_ADDR_ISP + 0x126C)
#define REG_VEC_S5                   (BASE_ADDR_ISP + 0x1270)
#define REG_VEC_SHOW                 (BASE_ADDR_ISP + 0x1274)
#define REG_POST_PEGAIN              (BASE_ADDR_ISP + 0x127C)
#define REG_POST_MEGAIN              (BASE_ADDR_ISP + 0x1280)
#define REG_POST_PETH                (BASE_ADDR_ISP + 0x1284)
#define REG_POST_METH                (BASE_ADDR_ISP + 0x1288)
#define REG_POST_PEMAX               (BASE_ADDR_ISP + 0x128C)
#define REG_POST_MEMAX               (BASE_ADDR_ISP + 0x1290)
#define REG_POST_E_K0                (BASE_ADDR_ISP + 0x1294)
#define REG_POST_E_K1                (BASE_ADDR_ISP + 0x1298)
#define REG_POST_E_K2                (BASE_ADDR_ISP + 0x129C)
#define REG_C_MAX                    (BASE_ADDR_ISP + 0x12A4)
#define REG_AUTO_DATA_CONTROL        (BASE_ADDR_ISP + 0x12A8)
#define REG_FORMAT                   (BASE_ADDR_ISP + 0x12AC)
#define REG_AE_FWX1_H                (BASE_ADDR_ISP + 0x12B4)
#define REG_AE_FWX1_L                (BASE_ADDR_ISP + 0x12B8)
#define REG_AE_FWX2_H                (BASE_ADDR_ISP + 0x12BC)
#define REG_AE_FWX2_L                (BASE_ADDR_ISP + 0x12C0)
#define REG_AE_FWY1_H                (BASE_ADDR_ISP + 0x12C4)
#define REG_AE_FWY1_L                (BASE_ADDR_ISP + 0x12C8)
#define REG_AE_FWY2_H                (BASE_ADDR_ISP + 0x12CC)
#define REG_AE_FWY2_L                (BASE_ADDR_ISP + 0x12D0)
#define REG_AE_CWX1_H                (BASE_ADDR_ISP + 0x12D4)
#define REG_AE_CWX1_L                (BASE_ADDR_ISP + 0x12D8)
#define REG_AE_CWX2_H                (BASE_ADDR_ISP + 0x12DC)
#define REG_AE_CWX2_L                (BASE_ADDR_ISP + 0x12E0)
#define REG_AE_CWY1_H                (BASE_ADDR_ISP + 0x12E4)
#define REG_AE_CWY1_L                (BASE_ADDR_ISP + 0x12E8)
#define REG_AE_CWY2_H                (BASE_ADDR_ISP + 0x12EC)
#define REG_AE_CWY2_L                (BASE_ADDR_ISP + 0x12F0)
#define REG_AE_XAXIS_H               (BASE_ADDR_ISP + 0x12F4)
#define REG_AE_XAXIS_L               (BASE_ADDR_ISP + 0x12F8)
#define REG_AE_YAXIS_H               (BASE_ADDR_ISP + 0x12FC)
#define REG_AE_YAXIS_L               (BASE_ADDR_ISP + 0x1300)
#define REG_AWB_WX1_H                (BASE_ADDR_ISP + 0x1304)
#define REG_AWB_WX1_L                (BASE_ADDR_ISP + 0x1308)
#define REG_AWB_WX2_H                (BASE_ADDR_ISP + 0x130C)
#define REG_AWB_WX2_L                (BASE_ADDR_ISP + 0x1310)
#define REG_AWB_WY1_H                (BASE_ADDR_ISP + 0x1314)
#define REG_AWB_WY1_L                (BASE_ADDR_ISP + 0x1318)
#define REG_AWB_WY2_H                (BASE_ADDR_ISP + 0x131C)
#define REG_AWB_WY2_L                (BASE_ADDR_ISP + 0x1320)
#define REG_AF_CWX1_H                (BASE_ADDR_ISP + 0x1324)
#define REG_AF_CWX1_L                (BASE_ADDR_ISP + 0x1328)
#define REG_AF_CWX2_H                (BASE_ADDR_ISP + 0x132C)
#define REG_AF_CWX2_L                (BASE_ADDR_ISP + 0x1330)
#define REG_AF_CWY1_H                (BASE_ADDR_ISP + 0x1334)
#define REG_AF_CWY1_L                (BASE_ADDR_ISP + 0x1338)
#define REG_AF_CWY2_H                (BASE_ADDR_ISP + 0x133C)
#define REG_AF_CWY2_L                (BASE_ADDR_ISP + 0x1340)
#define REG_AF_CWEIGHT               (BASE_ADDR_ISP + 0x1344)
#define REG_AF_EDGE_TH               (BASE_ADDR_ISP + 0x1348)
#define REG_AF_EDGE_SUM3             (BASE_ADDR_ISP + 0x134C)
#define REG_AF_EDGE_SUM2             (BASE_ADDR_ISP + 0x1350)
#define REG_AF_EDGE_SUM1             (BASE_ADDR_ISP + 0x1354)
#define REG_AF_EDGE_SUM0             (BASE_ADDR_ISP + 0x1358)
#define REG_WINDOWX1_H               (BASE_ADDR_ISP + 0x1360)
#define REG_WINDOWX1_L               (BASE_ADDR_ISP + 0x1364)
#define REG_WINDOWX2_H               (BASE_ADDR_ISP + 0x1368)
#define REG_WINDOWX2_L               (BASE_ADDR_ISP + 0x136C)
#define REG_WINDOWY1_H               (BASE_ADDR_ISP + 0x1370)
#define REG_WINDOWY1_L               (BASE_ADDR_ISP + 0x1374)
#define REG_WINDOWY2_H               (BASE_ADDR_ISP + 0x1378)
#define REG_WINDOWY2_L               (BASE_ADDR_ISP + 0x137C)
#define REG_AUTO_VSTART_H            (BASE_ADDR_ISP + 0x1384)
#define REG_AUTO_VSTART_L            (BASE_ADDR_ISP + 0x1388)
#define REG_AUTO_VSTOP_H             (BASE_ADDR_ISP + 0x138C)
#define REG_AUTO_VSTOP_L             (BASE_ADDR_ISP + 0x1390)
#define REG_AUTO_AEVSTART_H          (BASE_ADDR_ISP + 0x1394)
#define REG_AUTO_AEVSTART_L          (BASE_ADDR_ISP + 0x1398)
#define REG_SDCT_CTRL_0              (BASE_ADDR_ISP + 0x1410)
#define REG_SDCT_CTRL_1              (BASE_ADDR_ISP + 0x1414)
#define REG_NR_NA                    (BASE_ADDR_ISP + 0x141C)
#define REG_NR_NB                    (BASE_ADDR_ISP + 0x1420)
#define REG_NR_SGAIN                 (BASE_ADDR_ISP + 0x1424)
#define REG_SDCT_GGAIN_MANUAL        (BASE_ADDR_ISP + 0x1428)
#define REG_SDCT_TH_MUL_CH0          (BASE_ADDR_ISP + 0x142C)
#define REG_SDCT_TH_MUL_CH1          (BASE_ADDR_ISP + 0x1430)
#define REG_SDCT_TH_MUL_CH2          (BASE_ADDR_ISP + 0x1434)
#define REG_SDCT_TH_MUL_CH3          (BASE_ADDR_ISP + 0x1438)
#define REG_SDCT_MIX_RATIO           (BASE_ADDR_ISP + 0x143C)
#define REG_SDCT_NZC_ATT             (BASE_ADDR_ISP + 0x1440)
#define REG_SDCT_TBL_00_X01          (BASE_ADDR_ISP + 0x1444)
#define REG_SDCT_TBL_01_X01          (BASE_ADDR_ISP + 0x1448)
#define REG_SDCT_TBL_02_X01          (BASE_ADDR_ISP + 0x144C)
#define REG_SDCT_TBL_03_X01          (BASE_ADDR_ISP + 0x1450)
#define REG_SDCT_TBL_04_X01          (BASE_ADDR_ISP + 0x1454)
#define REG_SDCT_TBL_05_X01          (BASE_ADDR_ISP + 0x1458)
#define REG_SDCT_TBL_06_X01          (BASE_ADDR_ISP + 0x145C)
#define REG_SDCT_TBL_07_X01          (BASE_ADDR_ISP + 0x1460)
#define REG_SDCT_TBL_08_X01          (BASE_ADDR_ISP + 0x1464)
#define REG_SDCT_TBL_09_X01          (BASE_ADDR_ISP + 0x1468)
#define REG_SDCT_TBL_10_X01          (BASE_ADDR_ISP + 0x146C)
#define REG_SDCT_TBL_11_X01          (BASE_ADDR_ISP + 0x1470)
#define REG_SDCT_TBL_12_X01          (BASE_ADDR_ISP + 0x1474)
#define REG_SDCT_TBL_13_X01          (BASE_ADDR_ISP + 0x1478)
#define REG_SDCT_TBL_14_X01          (BASE_ADDR_ISP + 0x147C)
#define REG_SDCT_TBL_15_X01          (BASE_ADDR_ISP + 0x1480)
#define REG_SDCT_TBL_16_X01          (BASE_ADDR_ISP + 0x1484)
#define REG_SDCT_TBL_17_X01          (BASE_ADDR_ISP + 0x1488)
#define REG_SDCT_TBL_18_X01          (BASE_ADDR_ISP + 0x148C)
#define REG_SDCT_TBL_19_X01          (BASE_ADDR_ISP + 0x1490)
#define REG_SDCT_TBL_20_X01          (BASE_ADDR_ISP + 0x1494)
#define REG_SDCT_TBL_21_X01          (BASE_ADDR_ISP + 0x1498)
#define REG_SDCT_TBL_22_X01          (BASE_ADDR_ISP + 0x149C)
#define REG_SDCT_TBL_23_X01          (BASE_ADDR_ISP + 0x14A0)
#define REG_SDCT_TBL_24_X01          (BASE_ADDR_ISP + 0x14A4)
#define REG_SDCT_TBL_25_X01          (BASE_ADDR_ISP + 0x14A8)
#define REG_SDCT_TBL_26_X01          (BASE_ADDR_ISP + 0x14AC)
#define REG_SDCT_TBL_27_X01          (BASE_ADDR_ISP + 0x14B0)
#define REG_SDCT_TBL_28_X01          (BASE_ADDR_ISP + 0x14B4)
#define REG_SDCT_TBL_29_X01          (BASE_ADDR_ISP + 0x14B8)
#define REG_SDCT_TBL_30_X01          (BASE_ADDR_ISP + 0x14BC)
#define REG_SDCT_TBL_31_X01          (BASE_ADDR_ISP + 0x14C0)
#define REG_SDCT_TBL_00_X02          (BASE_ADDR_ISP + 0x14C4)
#define REG_SDCT_TBL_01_X02          (BASE_ADDR_ISP + 0x14C8)
#define REG_SDCT_TBL_02_X02          (BASE_ADDR_ISP + 0x14CC)
#define REG_SDCT_TBL_03_X02          (BASE_ADDR_ISP + 0x14D0)
#define REG_SDCT_TBL_04_X02          (BASE_ADDR_ISP + 0x14D4)
#define REG_SDCT_TBL_05_X02          (BASE_ADDR_ISP + 0x14D8)
#define REG_SDCT_TBL_06_X02          (BASE_ADDR_ISP + 0x14DC)
#define REG_SDCT_TBL_07_X02          (BASE_ADDR_ISP + 0x14E0)
#define REG_SDCT_TBL_08_X02          (BASE_ADDR_ISP + 0x14E4)
#define REG_SDCT_TBL_09_X02          (BASE_ADDR_ISP + 0x14E8)
#define REG_SDCT_TBL_10_X02          (BASE_ADDR_ISP + 0x14EC)
#define REG_SDCT_TBL_11_X02          (BASE_ADDR_ISP + 0x14F0)
#define REG_SDCT_TBL_12_X02          (BASE_ADDR_ISP + 0x14F4)
#define REG_SDCT_TBL_13_X02          (BASE_ADDR_ISP + 0x14F8)
#define REG_SDCT_TBL_14_X02          (BASE_ADDR_ISP + 0x14FC)
#define REG_SDCT_TBL_15_X02          (BASE_ADDR_ISP + 0x1500)
#define REG_SDCT_TBL_16_X02          (BASE_ADDR_ISP + 0x1504)
#define REG_SDCT_TBL_17_X02          (BASE_ADDR_ISP + 0x1508)
#define REG_SDCT_TBL_18_X02          (BASE_ADDR_ISP + 0x150C)
#define REG_SDCT_TBL_19_X02          (BASE_ADDR_ISP + 0x1510)
#define REG_SDCT_TBL_20_X02          (BASE_ADDR_ISP + 0x1514)
#define REG_SDCT_TBL_21_X02          (BASE_ADDR_ISP + 0x1518)
#define REG_SDCT_TBL_22_X02          (BASE_ADDR_ISP + 0x151C)
#define REG_SDCT_TBL_23_X02          (BASE_ADDR_ISP + 0x1520)
#define REG_SDCT_TBL_24_X02          (BASE_ADDR_ISP + 0x1524)
#define REG_SDCT_TBL_25_X02          (BASE_ADDR_ISP + 0x1528)
#define REG_SDCT_TBL_26_X02          (BASE_ADDR_ISP + 0x152C)
#define REG_SDCT_TBL_27_X02          (BASE_ADDR_ISP + 0x1530)
#define REG_SDCT_TBL_28_X02          (BASE_ADDR_ISP + 0x1534)
#define REG_SDCT_TBL_29_X02          (BASE_ADDR_ISP + 0x1538)
#define REG_SDCT_TBL_30_X02          (BASE_ADDR_ISP + 0x153C)
#define REG_SDCT_TBL_31_X02          (BASE_ADDR_ISP + 0x1540)
#define REG_SDCT_TBL_00_X04          (BASE_ADDR_ISP + 0x1544)
#define REG_SDCT_TBL_01_X04          (BASE_ADDR_ISP + 0x1548)
#define REG_SDCT_TBL_02_X04          (BASE_ADDR_ISP + 0x154C)
#define REG_SDCT_TBL_03_X04          (BASE_ADDR_ISP + 0x1550)
#define REG_SDCT_TBL_04_X04          (BASE_ADDR_ISP + 0x1554)
#define REG_SDCT_TBL_05_X04          (BASE_ADDR_ISP + 0x1558)
#define REG_SDCT_TBL_06_X04          (BASE_ADDR_ISP + 0x155C)
#define REG_SDCT_TBL_07_X04          (BASE_ADDR_ISP + 0x1560)
#define REG_SDCT_TBL_08_X04          (BASE_ADDR_ISP + 0x1564)
#define REG_SDCT_TBL_09_X04          (BASE_ADDR_ISP + 0x1568)
#define REG_SDCT_TBL_10_X04          (BASE_ADDR_ISP + 0x156C)
#define REG_SDCT_TBL_11_X04          (BASE_ADDR_ISP + 0x1570)
#define REG_SDCT_TBL_12_X04          (BASE_ADDR_ISP + 0x1574)
#define REG_SDCT_TBL_13_X04          (BASE_ADDR_ISP + 0x1578)
#define REG_SDCT_TBL_14_X04          (BASE_ADDR_ISP + 0x157C)
#define REG_SDCT_TBL_15_X04          (BASE_ADDR_ISP + 0x1580)
#define REG_SDCT_TBL_16_X04          (BASE_ADDR_ISP + 0x1584)
#define REG_SDCT_TBL_17_X04          (BASE_ADDR_ISP + 0x1588)
#define REG_SDCT_TBL_18_X04          (BASE_ADDR_ISP + 0x158C)
#define REG_SDCT_TBL_19_X04          (BASE_ADDR_ISP + 0x1590)
#define REG_SDCT_TBL_20_X04          (BASE_ADDR_ISP + 0x1594)
#define REG_SDCT_TBL_21_X04          (BASE_ADDR_ISP + 0x1598)
#define REG_SDCT_TBL_22_X04          (BASE_ADDR_ISP + 0x159C)
#define REG_SDCT_TBL_23_X04          (BASE_ADDR_ISP + 0x15A0)
#define REG_SDCT_TBL_24_X04          (BASE_ADDR_ISP + 0x15A4)
#define REG_SDCT_TBL_25_X04          (BASE_ADDR_ISP + 0x15A8)
#define REG_SDCT_TBL_26_X04          (BASE_ADDR_ISP + 0x15AC)
#define REG_SDCT_TBL_27_X04          (BASE_ADDR_ISP + 0x15B0)
#define REG_SDCT_TBL_28_X04          (BASE_ADDR_ISP + 0x15B4)
#define REG_SDCT_TBL_29_X04          (BASE_ADDR_ISP + 0x15B8)
#define REG_SDCT_TBL_30_X04          (BASE_ADDR_ISP + 0x15BC)
#define REG_SDCT_TBL_31_X04          (BASE_ADDR_ISP + 0x15C0)
#define REG_SDCT_TBL_00_X08          (BASE_ADDR_ISP + 0x15C4)
#define REG_SDCT_TBL_01_X08          (BASE_ADDR_ISP + 0x15C8)
#define REG_SDCT_TBL_02_X08          (BASE_ADDR_ISP + 0x15CC)
#define REG_SDCT_TBL_03_X08          (BASE_ADDR_ISP + 0x15D0)
#define REG_SDCT_TBL_04_X08          (BASE_ADDR_ISP + 0x15D4)
#define REG_SDCT_TBL_05_X08          (BASE_ADDR_ISP + 0x15D8)
#define REG_SDCT_TBL_06_X08          (BASE_ADDR_ISP + 0x15DC)
#define REG_SDCT_TBL_07_X08          (BASE_ADDR_ISP + 0x15E0)
#define REG_SDCT_TBL_08_X08          (BASE_ADDR_ISP + 0x15E4)
#define REG_SDCT_TBL_09_X08          (BASE_ADDR_ISP + 0x15E8)
#define REG_SDCT_TBL_10_X08          (BASE_ADDR_ISP + 0x15EC)
#define REG_SDCT_TBL_11_X08          (BASE_ADDR_ISP + 0x15F0)
#define REG_SDCT_TBL_12_X08          (BASE_ADDR_ISP + 0x15F4)
#define REG_SDCT_TBL_13_X08          (BASE_ADDR_ISP + 0x15F8)
#define REG_SDCT_TBL_14_X08          (BASE_ADDR_ISP + 0x15FC)
#define REG_SDCT_TBL_15_X08          (BASE_ADDR_ISP + 0x1600)
#define REG_SDCT_TBL_16_X08          (BASE_ADDR_ISP + 0x1604)
#define REG_SDCT_TBL_17_X08          (BASE_ADDR_ISP + 0x1608)
#define REG_SDCT_TBL_18_X08          (BASE_ADDR_ISP + 0x160C)
#define REG_SDCT_TBL_19_X08          (BASE_ADDR_ISP + 0x1610)
#define REG_SDCT_TBL_20_X08          (BASE_ADDR_ISP + 0x1614)
#define REG_SDCT_TBL_21_X08          (BASE_ADDR_ISP + 0x1618)
#define REG_SDCT_TBL_22_X08          (BASE_ADDR_ISP + 0x161C)
#define REG_SDCT_TBL_23_X08          (BASE_ADDR_ISP + 0x1620)
#define REG_SDCT_TBL_24_X08          (BASE_ADDR_ISP + 0x1624)
#define REG_SDCT_TBL_25_X08          (BASE_ADDR_ISP + 0x1628)
#define REG_SDCT_TBL_26_X08          (BASE_ADDR_ISP + 0x162C)
#define REG_SDCT_TBL_27_X08          (BASE_ADDR_ISP + 0x1630)
#define REG_SDCT_TBL_28_X08          (BASE_ADDR_ISP + 0x1634)
#define REG_SDCT_TBL_29_X08          (BASE_ADDR_ISP + 0x1638)
#define REG_SDCT_TBL_30_X08          (BASE_ADDR_ISP + 0x163C)
#define REG_SDCT_TBL_31_X08          (BASE_ADDR_ISP + 0x1640)
#define REG_SDCT_TBL_00_X16          (BASE_ADDR_ISP + 0x1644)
#define REG_SDCT_TBL_01_X16          (BASE_ADDR_ISP + 0x1648)
#define REG_SDCT_TBL_02_X16          (BASE_ADDR_ISP + 0x164C)
#define REG_SDCT_TBL_03_X16          (BASE_ADDR_ISP + 0x1650)
#define REG_SDCT_TBL_04_X16          (BASE_ADDR_ISP + 0x1654)
#define REG_SDCT_TBL_05_X16          (BASE_ADDR_ISP + 0x1658)
#define REG_SDCT_TBL_06_X16          (BASE_ADDR_ISP + 0x165C)
#define REG_SDCT_TBL_07_X16          (BASE_ADDR_ISP + 0x1660)
#define REG_SDCT_TBL_08_X16          (BASE_ADDR_ISP + 0x1664)
#define REG_SDCT_TBL_09_X16          (BASE_ADDR_ISP + 0x1668)
#define REG_SDCT_TBL_10_X16          (BASE_ADDR_ISP + 0x166C)
#define REG_SDCT_TBL_11_X16          (BASE_ADDR_ISP + 0x1670)
#define REG_SDCT_TBL_12_X16          (BASE_ADDR_ISP + 0x1674)
#define REG_SDCT_TBL_13_X16          (BASE_ADDR_ISP + 0x1678)
#define REG_SDCT_TBL_14_X16          (BASE_ADDR_ISP + 0x167C)
#define REG_SDCT_TBL_15_X16          (BASE_ADDR_ISP + 0x1680)
#define REG_SDCT_TBL_16_X16          (BASE_ADDR_ISP + 0x1684)
#define REG_SDCT_TBL_17_X16          (BASE_ADDR_ISP + 0x1688)
#define REG_SDCT_TBL_18_X16          (BASE_ADDR_ISP + 0x168C)
#define REG_SDCT_TBL_19_X16          (BASE_ADDR_ISP + 0x1690)
#define REG_SDCT_TBL_20_X16          (BASE_ADDR_ISP + 0x1694)
#define REG_SDCT_TBL_21_X16          (BASE_ADDR_ISP + 0x1698)
#define REG_SDCT_TBL_22_X16          (BASE_ADDR_ISP + 0x169C)
#define REG_SDCT_TBL_23_X16          (BASE_ADDR_ISP + 0x16A0)
#define REG_SDCT_TBL_24_X16          (BASE_ADDR_ISP + 0x16A4)
#define REG_SDCT_TBL_25_X16          (BASE_ADDR_ISP + 0x16A8)
#define REG_SDCT_TBL_26_X16          (BASE_ADDR_ISP + 0x16AC)
#define REG_SDCT_TBL_27_X16          (BASE_ADDR_ISP + 0x16B0)
#define REG_SDCT_TBL_28_X16          (BASE_ADDR_ISP + 0x16B4)
#define REG_SDCT_TBL_29_X16          (BASE_ADDR_ISP + 0x16B8)
#define REG_SDCT_TBL_30_X16          (BASE_ADDR_ISP + 0x16BC)
#define REG_SDCT_TBL_31_X16          (BASE_ADDR_ISP + 0x16C0)
#define REG_SDCT_TBL_00_X32          (BASE_ADDR_ISP + 0x16C4)
#define REG_SDCT_TBL_01_X32          (BASE_ADDR_ISP + 0x16C8)
#define REG_SDCT_TBL_02_X32          (BASE_ADDR_ISP + 0x16CC)
#define REG_SDCT_TBL_03_X32          (BASE_ADDR_ISP + 0x16D0)
#define REG_SDCT_TBL_04_X32          (BASE_ADDR_ISP + 0x16D4)
#define REG_SDCT_TBL_05_X32          (BASE_ADDR_ISP + 0x16D8)
#define REG_SDCT_TBL_06_X32          (BASE_ADDR_ISP + 0x16DC)
#define REG_SDCT_TBL_07_X32          (BASE_ADDR_ISP + 0x16E0)
#define REG_SDCT_TBL_08_X32          (BASE_ADDR_ISP + 0x16E4)
#define REG_SDCT_TBL_09_X32          (BASE_ADDR_ISP + 0x16E8)
#define REG_SDCT_TBL_10_X32          (BASE_ADDR_ISP + 0x16EC)
#define REG_SDCT_TBL_11_X32          (BASE_ADDR_ISP + 0x16F0)
#define REG_SDCT_TBL_12_X32          (BASE_ADDR_ISP + 0x16F4)
#define REG_SDCT_TBL_13_X32          (BASE_ADDR_ISP + 0x16F8)
#define REG_SDCT_TBL_14_X32          (BASE_ADDR_ISP + 0x16FC)
#define REG_SDCT_TBL_15_X32          (BASE_ADDR_ISP + 0x1700)
#define REG_SDCT_TBL_16_X32          (BASE_ADDR_ISP + 0x1704)
#define REG_SDCT_TBL_17_X32          (BASE_ADDR_ISP + 0x1708)
#define REG_SDCT_TBL_18_X32          (BASE_ADDR_ISP + 0x170C)
#define REG_SDCT_TBL_19_X32          (BASE_ADDR_ISP + 0x1710)
#define REG_SDCT_TBL_20_X32          (BASE_ADDR_ISP + 0x1714)
#define REG_SDCT_TBL_21_X32          (BASE_ADDR_ISP + 0x1718)
#define REG_SDCT_TBL_22_X32          (BASE_ADDR_ISP + 0x171C)
#define REG_SDCT_TBL_23_X32          (BASE_ADDR_ISP + 0x1720)
#define REG_SDCT_TBL_24_X32          (BASE_ADDR_ISP + 0x1724)
#define REG_SDCT_TBL_25_X32          (BASE_ADDR_ISP + 0x1728)
#define REG_SDCT_TBL_26_X32          (BASE_ADDR_ISP + 0x172C)
#define REG_SDCT_TBL_27_X32          (BASE_ADDR_ISP + 0x1730)
#define REG_SDCT_TBL_28_X32          (BASE_ADDR_ISP + 0x1734)
#define REG_SDCT_TBL_29_X32          (BASE_ADDR_ISP + 0x1738)
#define REG_SDCT_TBL_30_X32          (BASE_ADDR_ISP + 0x173C)
#define REG_SDCT_TBL_31_X32          (BASE_ADDR_ISP + 0x1740)
#define REG_SDCT_TBL_00_X64          (BASE_ADDR_ISP + 0x1744)
#define REG_SDCT_TBL_01_X64          (BASE_ADDR_ISP + 0x1748)
#define REG_SDCT_TBL_02_X64          (BASE_ADDR_ISP + 0x174C)
#define REG_SDCT_TBL_03_X64          (BASE_ADDR_ISP + 0x1750)
#define REG_SDCT_TBL_04_X64          (BASE_ADDR_ISP + 0x1754)
#define REG_SDCT_TBL_05_X64          (BASE_ADDR_ISP + 0x1758)
#define REG_SDCT_TBL_06_X64          (BASE_ADDR_ISP + 0x175C)
#define REG_SDCT_TBL_07_X64          (BASE_ADDR_ISP + 0x1760)
#define REG_SDCT_TBL_08_X64          (BASE_ADDR_ISP + 0x1764)
#define REG_SDCT_TBL_09_X64          (BASE_ADDR_ISP + 0x1768)
#define REG_SDCT_TBL_10_X64          (BASE_ADDR_ISP + 0x176C)
#define REG_SDCT_TBL_11_X64          (BASE_ADDR_ISP + 0x1770)
#define REG_SDCT_TBL_12_X64          (BASE_ADDR_ISP + 0x1774)
#define REG_SDCT_TBL_13_X64          (BASE_ADDR_ISP + 0x1778)
#define REG_SDCT_TBL_14_X64          (BASE_ADDR_ISP + 0x177C)
#define REG_SDCT_TBL_15_X64          (BASE_ADDR_ISP + 0x1780)
#define REG_SDCT_TBL_16_X64          (BASE_ADDR_ISP + 0x1784)
#define REG_SDCT_TBL_17_X64          (BASE_ADDR_ISP + 0x1788)
#define REG_SDCT_TBL_18_X64          (BASE_ADDR_ISP + 0x178C)
#define REG_SDCT_TBL_19_X64          (BASE_ADDR_ISP + 0x1790)
#define REG_SDCT_TBL_20_X64          (BASE_ADDR_ISP + 0x1794)
#define REG_SDCT_TBL_21_X64          (BASE_ADDR_ISP + 0x1798)
#define REG_SDCT_TBL_22_X64          (BASE_ADDR_ISP + 0x179C)
#define REG_SDCT_TBL_23_X64          (BASE_ADDR_ISP + 0x17A0)
#define REG_SDCT_TBL_24_X64          (BASE_ADDR_ISP + 0x17A4)
#define REG_SDCT_TBL_25_X64          (BASE_ADDR_ISP + 0x17A8)
#define REG_SDCT_TBL_26_X64          (BASE_ADDR_ISP + 0x17AC)
#define REG_SDCT_TBL_27_X64          (BASE_ADDR_ISP + 0x17B0)
#define REG_SDCT_TBL_28_X64          (BASE_ADDR_ISP + 0x17B4)
#define REG_SDCT_TBL_29_X64          (BASE_ADDR_ISP + 0x17B8)
#define REG_SDCT_TBL_30_X64          (BASE_ADDR_ISP + 0x17BC)
#define REG_SDCT_TBL_31_X64          (BASE_ADDR_ISP + 0x17C0)

#define REG_FRONT_REF0               (BASE_ADDR_ISP + 0x4F8 )
#define REG_FRONT_REF1               (BASE_ADDR_ISP + 0x4FC )
#define REG_FRONT_REF2               (BASE_ADDR_ISP + 0x500 )
#define REG_FRONT_REF3               (BASE_ADDR_ISP + 0x504 )
#define REG_FRONT_REF4               (BASE_ADDR_ISP + 0x508 )
/* Dummy Region Start */
#define REG_BR_STR					 (BASE_ADDR_ISP + 0x540 )
#define REG_CONT_STR				 (BASE_ADDR_ISP + 0x544 )
#define REG_NR_STR					 (BASE_ADDR_ISP + 0x548 )
#define REG_BLF_STR					 (BASE_ADDR_ISP + 0x54C )
#define REG_NF_STR					 (BASE_ADDR_ISP + 0x550 )
#define REG_SHARP_STR                (BASE_ADDR_ISP + 0x554 )
#define REG_SENSEUP                  (BASE_ADDR_ISP + 0x558 )

#define REG_MIRROR_VIEW              (BASE_ADDR_ISP + 0x560 )

#define REG_DN_EN                    (BASE_ADDR_ISP + 0x570 )
#define REG_DN_MODE                  (BASE_ADDR_ISP + 0x574 )
#define REG_D2N_LEVEL                (BASE_ADDR_ISP + 0x578 )
#define REG_N2D_LEVEL                (BASE_ADDR_ISP + 0x57C )
#define REG_DN_TR_DELAY              (BASE_ADDR_ISP + 0x580 )

#define REG_DN_LED_TH1               (BASE_ADDR_ISP + 0x584 )
#define REG_DN_LED_TH2               (BASE_ADDR_ISP + 0x588 )
#define REG_DN_D2N_TIME              (BASE_ADDR_ISP + 0x58C )
#define REG_DN_N2D_TIME              (BASE_ADDR_ISP + 0x590 )
#define REG_MIR_DUTY_H               (BASE_ADDR_ISP + 0x594 )
#define REG_MIR_DUTY_L               (BASE_ADDR_ISP + 0x598 )
#define REG_MIR_PERIOD_H             (BASE_ADDR_ISP + 0x59C )
#define REG_MIR_PERIOD_L             (BASE_ADDR_ISP + 0x5A0 )
#define REG_MIR_FRAME_SIZE           (BASE_ADDR_ISP + 0x5A4 )
#define REG_MIR_FREQ_SCALE           (BASE_ADDR_ISP + 0x5A8 )

#define REG_LUMA                     (BASE_ADDR_ISP + 0x610 )
#define REG_GLOBAL_GAIN              (BASE_ADDR_ISP + 0x614 )
#define REG_HNR_ONOFF                (BASE_ADDR_ISP + 0x618 )

#define REG_HNR_XREF0                (BASE_ADDR_ISP + 0x620 )
#define REG_HNR_XREF1                (BASE_ADDR_ISP + 0x624 )
#define REG_HNR_XREF2                (BASE_ADDR_ISP + 0x628 )
#define REG_HNR_XREF3                (BASE_ADDR_ISP + 0x62C )
#define REG_HNR_XREF4                (BASE_ADDR_ISP + 0x630 )

#define REG_HNR_GAIN_THR             (BASE_ADDR_ISP + 0x648 )

#define REG_HNR_TFBAND_0             (BASE_ADDR_ISP + 0x650 )
#define REG_HNR_TFBAND_1             (BASE_ADDR_ISP + 0x654 )
#define REG_HNR_TFBAND_2             (BASE_ADDR_ISP + 0x658 )
#define REG_HNR_TFBAND_3             (BASE_ADDR_ISP + 0x65C )
#define REG_HNR_TFBAND_4             (BASE_ADDR_ISP + 0x660 )
#define REG_HNR_SFBAND_0             (BASE_ADDR_ISP + 0x664 )
#define REG_HNR_SFBAND_1             (BASE_ADDR_ISP + 0x668 )
#define REG_HNR_SFBAND_2             (BASE_ADDR_ISP + 0x66C )
#define REG_HNR_SFBAND_3             (BASE_ADDR_ISP + 0x670 )
#define REG_HNR_SFBAND_4             (BASE_ADDR_ISP + 0x674 )
#define REG_HNR_CONTROL_0            (BASE_ADDR_ISP + 0x678 )
#define REG_HNR_CONTROL_1            (BASE_ADDR_ISP + 0x67C )
#define REG_HNR_CONTROL_2            (BASE_ADDR_ISP + 0x680 )
#define REG_HNR_CONTROL_3            (BASE_ADDR_ISP + 0x684 )
#define REG_HNR_CONTROL_4            (BASE_ADDR_ISP + 0x688 )

#define REG_I2C_BUSY                 (BASE_ADDR_ISP + 0x6B0 )

#define REG_DAY_BR_STR				 (BASE_ADDR_ISP + 0x6C0 )
#define REG_DAY_CONT_STR			 (BASE_ADDR_ISP + 0x6C4 )
#define REG_DAY_NR_STR				 (BASE_ADDR_ISP + 0x6C8 )
#define REG_DAY_BLF_STR				 (BASE_ADDR_ISP + 0x6CC )
#define REG_DAY_NF_STR				 (BASE_ADDR_ISP + 0x6D0 )
#define REG_DAY_SHARP_STR            (BASE_ADDR_ISP + 0x6D4 )
#define REG_NIGHT_BR_STR			 (BASE_ADDR_ISP + 0x6D8 )
#define REG_NIGHT_CONT_STR			 (BASE_ADDR_ISP + 0x6DC )
#define REG_NIGHT_NR_STR			 (BASE_ADDR_ISP + 0x6E0 )
#define REG_NIGHT_BLF_STR			 (BASE_ADDR_ISP + 0x6E4 )
#define REG_NIGHT_NF_STR			 (BASE_ADDR_ISP + 0x6E8 )
#define REG_NIGHT_SHARP_STR          (BASE_ADDR_ISP + 0x6EC )

#define REG_RAMPC_REF0               (BASE_ADDR_ISP + 0x6F0 )
#define REG_RAMPC_REF1               (BASE_ADDR_ISP + 0x6F4 )
#define REG_RAMPC_REF2               (BASE_ADDR_ISP + 0x6F8 )
#define REG_RAMPC_REF3               (BASE_ADDR_ISP + 0x6FC )
#define REG_RAMPC_REF4               (BASE_ADDR_ISP + 0x700 )
#define REG_COMPB_REF0               (BASE_ADDR_ISP + 0x704 )
#define REG_COMPB_REF1               (BASE_ADDR_ISP + 0x708 )
#define REG_COMPB_REF2               (BASE_ADDR_ISP + 0x70C )
#define REG_COMPB_REF3               (BASE_ADDR_ISP + 0x710 )
#define REG_COMPB_REF4               (BASE_ADDR_ISP + 0x714 )
#define REG_RAMPC_RESET_DELAY        (BASE_ADDR_ISP + 0x718 )

#define BASE_ADDR_SRAM				 (0x00000000 + 0x1D000)
//#define REG_TEST_ID                  (BASE_ADDR_SRAM + 0x044)
//#define REG_TEST_ID                  (0x05006004)
#define REG_GENLOCK_STATUS           (0x0001004C)
#define REG_TEST_ID                  (0x00015800)
#define REG_TEST_SEQ                 (BASE_ADDR_SRAM + 0x048)
#define REG_TEST_START               (BASE_ADDR_SRAM + 0x04C)
#define REG_TEST_DATA                (BASE_ADDR_SRAM + 0x110)
//#define REG_TEST_ID                  (BASE_ADDR_ISP + 0x544)
//#define REG_TEST_SEQ                 (BASE_ADDR_ISP + 0x548)
//#define REG_TEST_START               (BASE_ADDR_ISP + 0x54C)
//#define REG_TEST_DATA                (BASE_ADDR_ISP + 0x550)
#define REG_TEST_SCRATCH             (BASE_ADDR_SRAM + 0x510)


/* Dummy Region End */

/* HNR */
#define REG_HNR_CONTROL              (BASE_ADDR_ISP + 0x4020)
#define REG_HNR_IMG_SIZE             (BASE_ADDR_ISP + 0x4024)
#define REG_HNR_TFOFFS               (BASE_ADDR_ISP + 0x4028)
#define REG_HNR_TFBAND               (BASE_ADDR_ISP + 0x402C)
#define REG_HNR_PIXCNT               (BASE_ADDR_ISP + 0x4030)
#define REG_HNR_SFOFFS               (BASE_ADDR_ISP + 0x4034)
#define REG_HNR_SFBAND               (BASE_ADDR_ISP + 0x4038)
#define REG_HNR_DELAY                (BASE_ADDR_ISP + 0x403C)

/* System Block */

#ifdef __cplusplus
}
#endif

#endif //__ISPREG_H__
